// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: proto/devicebridge/v1/common.proto

package devicebridgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeviceStatus represents the current state of a device
type DeviceStatus int32

const (
	DeviceStatus_DEVICE_STATUS_UNSPECIFIED DeviceStatus = 0
	DeviceStatus_DEVICE_STATUS_UNKNOWN     DeviceStatus = 1
	DeviceStatus_DEVICE_STATUS_READY       DeviceStatus = 2
	DeviceStatus_DEVICE_STATUS_DEGRADED    DeviceStatus = 3
	DeviceStatus_DEVICE_STATUS_OFFLINE     DeviceStatus = 4
	DeviceStatus_DEVICE_STATUS_ERROR       DeviceStatus = 5
)

// Enum value maps for DeviceStatus.
var (
	DeviceStatus_name = map[int32]string{
		0: "DEVICE_STATUS_UNSPECIFIED",
		1: "DEVICE_STATUS_UNKNOWN",
		2: "DEVICE_STATUS_READY",
		3: "DEVICE_STATUS_DEGRADED",
		4: "DEVICE_STATUS_OFFLINE",
		5: "DEVICE_STATUS_ERROR",
	}
	DeviceStatus_value = map[string]int32{
		"DEVICE_STATUS_UNSPECIFIED": 0,
		"DEVICE_STATUS_UNKNOWN":     1,
		"DEVICE_STATUS_READY":       2,
		"DEVICE_STATUS_DEGRADED":    3,
		"DEVICE_STATUS_OFFLINE":     4,
		"DEVICE_STATUS_ERROR":       5,
	}
)

func (x DeviceStatus) Enum() *DeviceStatus {
	p := new(DeviceStatus)
	*p = x
	return p
}

func (x DeviceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_devicebridge_v1_common_proto_enumTypes[0].Descriptor()
}

func (DeviceStatus) Type() protoreflect.EnumType {
	return &file_proto_devicebridge_v1_common_proto_enumTypes[0]
}

func (x DeviceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceStatus.Descriptor instead.
func (DeviceStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_common_proto_rawDescGZIP(), []int{0}
}

// JobStatus represents job execution state
type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	JobStatus_JOB_STATUS_PENDING     JobStatus = 1
	JobStatus_JOB_STATUS_IN_PROGRESS JobStatus = 2
	JobStatus_JOB_STATUS_COMPLETED   JobStatus = 3
	JobStatus_JOB_STATUS_FAILED      JobStatus = 4
	JobStatus_JOB_STATUS_CANCELLED   JobStatus = 5
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_PENDING",
		2: "JOB_STATUS_IN_PROGRESS",
		3: "JOB_STATUS_COMPLETED",
		4: "JOB_STATUS_FAILED",
		5: "JOB_STATUS_CANCELLED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_PENDING":     1,
		"JOB_STATUS_IN_PROGRESS": 2,
		"JOB_STATUS_COMPLETED":   3,
		"JOB_STATUS_FAILED":      4,
		"JOB_STATUS_CANCELLED":   5,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_devicebridge_v1_common_proto_enumTypes[1].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_proto_devicebridge_v1_common_proto_enumTypes[1]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_common_proto_rawDescGZIP(), []int{1}
}

// DeviceHealth represents device health information
type DeviceHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        DeviceStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=devicebridge.v1.DeviceStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceHealth) Reset() {
	*x = DeviceHealth{}
	mi := &file_proto_devicebridge_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceHealth) ProtoMessage() {}

func (x *DeviceHealth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceHealth.ProtoReflect.Descriptor instead.
func (*DeviceHealth) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceHealth) GetStatus() DeviceStatus {
	if x != nil {
		return x.Status
	}
	return DeviceStatus_DEVICE_STATUS_UNSPECIFIED
}

func (x *DeviceHealth) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeviceHealth) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DeviceHealth) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

// Device represents a hardware device
type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Vendor        string                 `protobuf:"bytes,4,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	Connection    *ConnectionInfo        `protobuf:"bytes,6,opt,name=connection,proto3" json:"connection,omitempty"`
	Health        *DeviceHealth          `protobuf:"bytes,7,opt,name=health,proto3" json:"health,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags          []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_proto_devicebridge_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *Device) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Device) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *Device) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Device) GetConnection() *ConnectionInfo {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *Device) GetHealth() *DeviceHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *Device) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *Device) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Device) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// ConnectionInfo describes how to connect to a device
type ConnectionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transport     string                 `protobuf:"bytes,1,opt,name=transport,proto3" json:"transport,omitempty"`                   // usb, serial, tcp
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`                       // IP address or device path
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`                            // Port for TCP connections
	BaudRate      int32                  `protobuf:"varint,4,opt,name=baud_rate,json=baudRate,proto3" json:"baud_rate,omitempty"`    // Baud rate for serial
	VendorId      int32                  `protobuf:"varint,5,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`    // USB vendor ID
	ProductId     int32                  `protobuf:"varint,6,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"` // USB product ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionInfo) Reset() {
	*x = ConnectionInfo{}
	mi := &file_proto_devicebridge_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionInfo) ProtoMessage() {}

func (x *ConnectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionInfo.ProtoReflect.Descriptor instead.
func (*ConnectionInfo) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectionInfo) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *ConnectionInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ConnectionInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ConnectionInfo) GetBaudRate() int32 {
	if x != nil {
		return x.BaudRate
	}
	return 0
}

func (x *ConnectionInfo) GetVendorId() int32 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

func (x *ConnectionInfo) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

// Job represents an asynchronous device operation
type Job struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	DeviceId       string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Status         JobStatus              `protobuf:"varint,4,opt,name=status,proto3,enum=devicebridge.v1.JobStatus" json:"status,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Error          string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,9,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_proto_devicebridge_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *Job) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Job) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Job) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Job) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *Job) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Job) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Job) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Job) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Job) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

var File_proto_devicebridge_v1_common_proto protoreflect.FileDescriptor

const file_proto_devicebridge_v1_common_proto_rawDesc = "" +
	"\n" +
	"\"proto/devicebridge/v1/common.proto\x12\x0fdevicebridge.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb8\x01\n" +
	"\fDeviceHealth\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.devicebridge.v1.DeviceStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\"\xb3\x03\n" +
	"\x06Device\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x16\n" +
	"\x06vendor\x18\x04 \x01(\tR\x06vendor\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12?\n" +
	"\n" +
	"connection\x18\x06 \x01(\v2\x1f.devicebridge.v1.ConnectionInfoR\n" +
	"connection\x125\n" +
	"\x06health\x18\a \x01(\v2\x1d.devicebridge.v1.DeviceHealthR\x06health\x127\n" +
	"\tlast_seen\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12A\n" +
	"\bmetadata\x18\t \x03(\v2%.devicebridge.v1.Device.MetadataEntryR\bmetadata\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb5\x01\n" +
	"\x0eConnectionInfo\x12\x1c\n" +
	"\ttransport\x18\x01 \x01(\tR\ttransport\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1b\n" +
	"\tbaud_rate\x18\x04 \x01(\x05R\bbaudRate\x12\x1b\n" +
	"\tvendor_id\x18\x05 \x01(\x05R\bvendorId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x06 \x01(\x05R\tproductId\"\xf5\x02\n" +
	"\x03Job\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x122\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1a.devicebridge.v1.JobStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12'\n" +
	"\x0fidempotency_key\x18\t \x01(\tR\x0eidempotencyKey*\xb1\x01\n" +
	"\fDeviceStatus\x12\x1d\n" +
	"\x19DEVICE_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DEVICE_STATUS_UNKNOWN\x10\x01\x12\x17\n" +
	"\x13DEVICE_STATUS_READY\x10\x02\x12\x1a\n" +
	"\x16DEVICE_STATUS_DEGRADED\x10\x03\x12\x19\n" +
	"\x15DEVICE_STATUS_OFFLINE\x10\x04\x12\x17\n" +
	"\x13DEVICE_STATUS_ERROR\x10\x05*\xa6\x01\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12JOB_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16JOB_STATUS_IN_PROGRESS\x10\x02\x12\x18\n" +
	"\x14JOB_STATUS_COMPLETED\x10\x03\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x04\x12\x18\n" +
	"\x14JOB_STATUS_CANCELLED\x10\x05BJZHgithub.com/Macber-eg/Flutter-Device/proto/devicebridge/v1;devicebridgev1b\x06proto3"

var (
	file_proto_devicebridge_v1_common_proto_rawDescOnce sync.Once
	file_proto_devicebridge_v1_common_proto_rawDescData []byte
)

func file_proto_devicebridge_v1_common_proto_rawDescGZIP() []byte {
	file_proto_devicebridge_v1_common_proto_rawDescOnce.Do(func() {
		file_proto_devicebridge_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_devicebridge_v1_common_proto_rawDesc), len(file_proto_devicebridge_v1_common_proto_rawDesc)))
	})
	return file_proto_devicebridge_v1_common_proto_rawDescData
}

var file_proto_devicebridge_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_devicebridge_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_devicebridge_v1_common_proto_goTypes = []any{
	(DeviceStatus)(0),             // 0: devicebridge.v1.DeviceStatus
	(JobStatus)(0),                // 1: devicebridge.v1.JobStatus
	(*DeviceHealth)(nil),          // 2: devicebridge.v1.DeviceHealth
	(*Device)(nil),                // 3: devicebridge.v1.Device
	(*ConnectionInfo)(nil),        // 4: devicebridge.v1.ConnectionInfo
	(*Job)(nil),                   // 5: devicebridge.v1.Job
	nil,                           // 6: devicebridge.v1.Device.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_proto_devicebridge_v1_common_proto_depIdxs = []int32{
	0,  // 0: devicebridge.v1.DeviceHealth.status:type_name -> devicebridge.v1.DeviceStatus
	7,  // 1: devicebridge.v1.DeviceHealth.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 2: devicebridge.v1.Device.connection:type_name -> devicebridge.v1.ConnectionInfo
	2,  // 3: devicebridge.v1.Device.health:type_name -> devicebridge.v1.DeviceHealth
	7,  // 4: devicebridge.v1.Device.last_seen:type_name -> google.protobuf.Timestamp
	6,  // 5: devicebridge.v1.Device.metadata:type_name -> devicebridge.v1.Device.MetadataEntry
	1,  // 6: devicebridge.v1.Job.status:type_name -> devicebridge.v1.JobStatus
	7,  // 7: devicebridge.v1.Job.created_at:type_name -> google.protobuf.Timestamp
	7,  // 8: devicebridge.v1.Job.started_at:type_name -> google.protobuf.Timestamp
	7,  // 9: devicebridge.v1.Job.completed_at:type_name -> google.protobuf.Timestamp
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_devicebridge_v1_common_proto_init() }
func file_proto_devicebridge_v1_common_proto_init() {
	if File_proto_devicebridge_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_devicebridge_v1_common_proto_rawDesc), len(file_proto_devicebridge_v1_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_devicebridge_v1_common_proto_goTypes,
		DependencyIndexes: file_proto_devicebridge_v1_common_proto_depIdxs,
		EnumInfos:         file_proto_devicebridge_v1_common_proto_enumTypes,
		MessageInfos:      file_proto_devicebridge_v1_common_proto_msgTypes,
	}.Build()
	File_proto_devicebridge_v1_common_proto = out.File
	file_proto_devicebridge_v1_common_proto_goTypes = nil
	file_proto_devicebridge_v1_common_proto_depIdxs = nil
}
