// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: proto/devicebridge/v1/display.proto

package devicebridgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ShowDisplayRequest shows text on customer display
type ShowDisplayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Lines         []string               `protobuf:"bytes,2,rep,name=lines,proto3" json:"lines,omitempty"`
	DurationMs    int32                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"` // 0 = permanent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowDisplayRequest) Reset() {
	*x = ShowDisplayRequest{}
	mi := &file_proto_devicebridge_v1_display_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowDisplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowDisplayRequest) ProtoMessage() {}

func (x *ShowDisplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_display_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowDisplayRequest.ProtoReflect.Descriptor instead.
func (*ShowDisplayRequest) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_display_proto_rawDescGZIP(), []int{0}
}

func (x *ShowDisplayRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ShowDisplayRequest) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *ShowDisplayRequest) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// ShowDisplayResponse confirms display update
type ShowDisplayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowDisplayResponse) Reset() {
	*x = ShowDisplayResponse{}
	mi := &file_proto_devicebridge_v1_display_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowDisplayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowDisplayResponse) ProtoMessage() {}

func (x *ShowDisplayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_display_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowDisplayResponse.ProtoReflect.Descriptor instead.
func (*ShowDisplayResponse) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_display_proto_rawDescGZIP(), []int{1}
}

func (x *ShowDisplayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ClearDisplayRequest clears the display
type ClearDisplayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearDisplayRequest) Reset() {
	*x = ClearDisplayRequest{}
	mi := &file_proto_devicebridge_v1_display_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearDisplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearDisplayRequest) ProtoMessage() {}

func (x *ClearDisplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_display_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearDisplayRequest.ProtoReflect.Descriptor instead.
func (*ClearDisplayRequest) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_display_proto_rawDescGZIP(), []int{2}
}

func (x *ClearDisplayRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// ClearDisplayResponse confirms clear operation
type ClearDisplayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearDisplayResponse) Reset() {
	*x = ClearDisplayResponse{}
	mi := &file_proto_devicebridge_v1_display_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearDisplayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearDisplayResponse) ProtoMessage() {}

func (x *ClearDisplayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_display_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearDisplayResponse.ProtoReflect.Descriptor instead.
func (*ClearDisplayResponse) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_display_proto_rawDescGZIP(), []int{3}
}

func (x *ClearDisplayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// SetBrightnessRequest sets display brightness
type SetBrightnessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Brightness    int32                  `protobuf:"varint,2,opt,name=brightness,proto3" json:"brightness,omitempty"` // 0-100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBrightnessRequest) Reset() {
	*x = SetBrightnessRequest{}
	mi := &file_proto_devicebridge_v1_display_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBrightnessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBrightnessRequest) ProtoMessage() {}

func (x *SetBrightnessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_display_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBrightnessRequest.ProtoReflect.Descriptor instead.
func (*SetBrightnessRequest) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_display_proto_rawDescGZIP(), []int{4}
}

func (x *SetBrightnessRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SetBrightnessRequest) GetBrightness() int32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

// SetBrightnessResponse confirms brightness change
type SetBrightnessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBrightnessResponse) Reset() {
	*x = SetBrightnessResponse{}
	mi := &file_proto_devicebridge_v1_display_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBrightnessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBrightnessResponse) ProtoMessage() {}

func (x *SetBrightnessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_display_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBrightnessResponse.ProtoReflect.Descriptor instead.
func (*SetBrightnessResponse) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_display_proto_rawDescGZIP(), []int{5}
}

func (x *SetBrightnessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_devicebridge_v1_display_proto protoreflect.FileDescriptor

const file_proto_devicebridge_v1_display_proto_rawDesc = "" +
	"\n" +
	"#proto/devicebridge/v1/display.proto\x12\x0fdevicebridge.v1\"h\n" +
	"\x12ShowDisplayRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05lines\x18\x02 \x03(\tR\x05lines\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x05R\n" +
	"durationMs\"/\n" +
	"\x13ShowDisplayResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"2\n" +
	"\x13ClearDisplayRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"0\n" +
	"\x14ClearDisplayResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"S\n" +
	"\x14SetBrightnessRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1e\n" +
	"\n" +
	"brightness\x18\x02 \x01(\x05R\n" +
	"brightness\"1\n" +
	"\x15SetBrightnessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessBJZHgithub.com/Macber-eg/Flutter-Device/proto/devicebridge/v1;devicebridgev1b\x06proto3"

var (
	file_proto_devicebridge_v1_display_proto_rawDescOnce sync.Once
	file_proto_devicebridge_v1_display_proto_rawDescData []byte
)

func file_proto_devicebridge_v1_display_proto_rawDescGZIP() []byte {
	file_proto_devicebridge_v1_display_proto_rawDescOnce.Do(func() {
		file_proto_devicebridge_v1_display_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_devicebridge_v1_display_proto_rawDesc), len(file_proto_devicebridge_v1_display_proto_rawDesc)))
	})
	return file_proto_devicebridge_v1_display_proto_rawDescData
}

var file_proto_devicebridge_v1_display_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_devicebridge_v1_display_proto_goTypes = []any{
	(*ShowDisplayRequest)(nil),    // 0: devicebridge.v1.ShowDisplayRequest
	(*ShowDisplayResponse)(nil),   // 1: devicebridge.v1.ShowDisplayResponse
	(*ClearDisplayRequest)(nil),   // 2: devicebridge.v1.ClearDisplayRequest
	(*ClearDisplayResponse)(nil),  // 3: devicebridge.v1.ClearDisplayResponse
	(*SetBrightnessRequest)(nil),  // 4: devicebridge.v1.SetBrightnessRequest
	(*SetBrightnessResponse)(nil), // 5: devicebridge.v1.SetBrightnessResponse
}
var file_proto_devicebridge_v1_display_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_devicebridge_v1_display_proto_init() }
func file_proto_devicebridge_v1_display_proto_init() {
	if File_proto_devicebridge_v1_display_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_devicebridge_v1_display_proto_rawDesc), len(file_proto_devicebridge_v1_display_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_devicebridge_v1_display_proto_goTypes,
		DependencyIndexes: file_proto_devicebridge_v1_display_proto_depIdxs,
		MessageInfos:      file_proto_devicebridge_v1_display_proto_msgTypes,
	}.Build()
	File_proto_devicebridge_v1_display_proto = out.File
	file_proto_devicebridge_v1_display_proto_goTypes = nil
	file_proto_devicebridge_v1_display_proto_depIdxs = nil
}
