// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: proto/devicebridge/v1/payment.proto

package devicebridgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PaymentState defines payment status
type PaymentState int32

const (
	PaymentState_PAYMENT_STATE_UNSPECIFIED PaymentState = 0
	PaymentState_PAYMENT_STATE_INITIATED   PaymentState = 1
	PaymentState_PAYMENT_STATE_IN_PROGRESS PaymentState = 2
	PaymentState_PAYMENT_STATE_APPROVED    PaymentState = 3
	PaymentState_PAYMENT_STATE_DECLINED    PaymentState = 4
	PaymentState_PAYMENT_STATE_CANCELLED   PaymentState = 5
	PaymentState_PAYMENT_STATE_TIMEOUT     PaymentState = 6
	PaymentState_PAYMENT_STATE_ERROR       PaymentState = 7
)

// Enum value maps for PaymentState.
var (
	PaymentState_name = map[int32]string{
		0: "PAYMENT_STATE_UNSPECIFIED",
		1: "PAYMENT_STATE_INITIATED",
		2: "PAYMENT_STATE_IN_PROGRESS",
		3: "PAYMENT_STATE_APPROVED",
		4: "PAYMENT_STATE_DECLINED",
		5: "PAYMENT_STATE_CANCELLED",
		6: "PAYMENT_STATE_TIMEOUT",
		7: "PAYMENT_STATE_ERROR",
	}
	PaymentState_value = map[string]int32{
		"PAYMENT_STATE_UNSPECIFIED": 0,
		"PAYMENT_STATE_INITIATED":   1,
		"PAYMENT_STATE_IN_PROGRESS": 2,
		"PAYMENT_STATE_APPROVED":    3,
		"PAYMENT_STATE_DECLINED":    4,
		"PAYMENT_STATE_CANCELLED":   5,
		"PAYMENT_STATE_TIMEOUT":     6,
		"PAYMENT_STATE_ERROR":       7,
	}
)

func (x PaymentState) Enum() *PaymentState {
	p := new(PaymentState)
	*p = x
	return p
}

func (x PaymentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_devicebridge_v1_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentState) Type() protoreflect.EnumType {
	return &file_proto_devicebridge_v1_payment_proto_enumTypes[0]
}

func (x PaymentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentState.Descriptor instead.
func (PaymentState) EnumDescriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_payment_proto_rawDescGZIP(), []int{0}
}

// StartPaymentRequest initiates a payment
type StartPaymentRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DeviceId          string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Amount            float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency          string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	MerchantReference string                 `protobuf:"bytes,4,opt,name=merchant_reference,json=merchantReference,proto3" json:"merchant_reference,omitempty"`
	Metadata          map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutMs         int32                  `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StartPaymentRequest) Reset() {
	*x = StartPaymentRequest{}
	mi := &file_proto_devicebridge_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPaymentRequest) ProtoMessage() {}

func (x *StartPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPaymentRequest.ProtoReflect.Descriptor instead.
func (*StartPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *StartPaymentRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *StartPaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *StartPaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *StartPaymentRequest) GetMerchantReference() string {
	if x != nil {
		return x.MerchantReference
	}
	return ""
}

func (x *StartPaymentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StartPaymentRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// StartPaymentResponse returns payment ID
type StartPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Status        PaymentState           `protobuf:"varint,2,opt,name=status,proto3,enum=devicebridge.v1.PaymentState" json:"status,omitempty"`
	InitiatedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=initiated_at,json=initiatedAt,proto3" json:"initiated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartPaymentResponse) Reset() {
	*x = StartPaymentResponse{}
	mi := &file_proto_devicebridge_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPaymentResponse) ProtoMessage() {}

func (x *StartPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPaymentResponse.ProtoReflect.Descriptor instead.
func (*StartPaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *StartPaymentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *StartPaymentResponse) GetStatus() PaymentState {
	if x != nil {
		return x.Status
	}
	return PaymentState_PAYMENT_STATE_UNSPECIFIED
}

func (x *StartPaymentResponse) GetInitiatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InitiatedAt
	}
	return nil
}

// CancelPaymentRequest cancels a payment
type CancelPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPaymentRequest) Reset() {
	*x = CancelPaymentRequest{}
	mi := &file_proto_devicebridge_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPaymentRequest) ProtoMessage() {}

func (x *CancelPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPaymentRequest.ProtoReflect.Descriptor instead.
func (*CancelPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *CancelPaymentRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CancelPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

// CancelPaymentResponse confirms cancellation
type CancelPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPaymentResponse) Reset() {
	*x = CancelPaymentResponse{}
	mi := &file_proto_devicebridge_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPaymentResponse) ProtoMessage() {}

func (x *CancelPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPaymentResponse.ProtoReflect.Descriptor instead.
func (*CancelPaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *CancelPaymentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetPaymentStatusRequest queries payment status
type GetPaymentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentStatusRequest) Reset() {
	*x = GetPaymentStatusRequest{}
	mi := &file_proto_devicebridge_v1_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentStatusRequest) ProtoMessage() {}

func (x *GetPaymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_payment_proto_rawDescGZIP(), []int{4}
}

func (x *GetPaymentStatusRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetPaymentStatusRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

// PaymentStatus represents payment state
type PaymentStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Status        PaymentState           `protobuf:"varint,2,opt,name=status,proto3,enum=devicebridge.v1.PaymentState" json:"status,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	CardType      string                 `protobuf:"bytes,5,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	Last_4        string                 `protobuf:"bytes,6,opt,name=last_4,json=last4,proto3" json:"last_4,omitempty"`
	ApprovalCode  string                 `protobuf:"bytes,7,opt,name=approval_code,json=approvalCode,proto3" json:"approval_code,omitempty"`
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	InitiatedAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=initiated_at,json=initiatedAt,proto3" json:"initiated_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentStatus) Reset() {
	*x = PaymentStatus{}
	mi := &file_proto_devicebridge_v1_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentStatus) ProtoMessage() {}

func (x *PaymentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentStatus.ProtoReflect.Descriptor instead.
func (*PaymentStatus) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_payment_proto_rawDescGZIP(), []int{5}
}

func (x *PaymentStatus) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *PaymentStatus) GetStatus() PaymentState {
	if x != nil {
		return x.Status
	}
	return PaymentState_PAYMENT_STATE_UNSPECIFIED
}

func (x *PaymentStatus) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentStatus) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentStatus) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *PaymentStatus) GetLast_4() string {
	if x != nil {
		return x.Last_4
	}
	return ""
}

func (x *PaymentStatus) GetApprovalCode() string {
	if x != nil {
		return x.ApprovalCode
	}
	return ""
}

func (x *PaymentStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PaymentStatus) GetInitiatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InitiatedAt
	}
	return nil
}

func (x *PaymentStatus) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// GetPaymentStatusResponse returns payment status
type GetPaymentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *PaymentStatus         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentStatusResponse) Reset() {
	*x = GetPaymentStatusResponse{}
	mi := &file_proto_devicebridge_v1_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentStatusResponse) ProtoMessage() {}

func (x *GetPaymentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentStatusResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_payment_proto_rawDescGZIP(), []int{6}
}

func (x *GetPaymentStatusResponse) GetStatus() *PaymentStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// PaymentEvent represents a payment state change
type PaymentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	Status        PaymentState           `protobuf:"varint,3,opt,name=status,proto3,enum=devicebridge.v1.PaymentState" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentEvent) Reset() {
	*x = PaymentEvent{}
	mi := &file_proto_devicebridge_v1_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentEvent) ProtoMessage() {}

func (x *PaymentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentEvent.ProtoReflect.Descriptor instead.
func (*PaymentEvent) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_payment_proto_rawDescGZIP(), []int{7}
}

func (x *PaymentEvent) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *PaymentEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *PaymentEvent) GetStatus() PaymentState {
	if x != nil {
		return x.Status
	}
	return PaymentState_PAYMENT_STATE_UNSPECIFIED
}

func (x *PaymentEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PaymentEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// SubscribePaymentRequest subscribes to payment events
type SubscribePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribePaymentRequest) Reset() {
	*x = SubscribePaymentRequest{}
	mi := &file_proto_devicebridge_v1_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribePaymentRequest) ProtoMessage() {}

func (x *SubscribePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribePaymentRequest.ProtoReflect.Descriptor instead.
func (*SubscribePaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_payment_proto_rawDescGZIP(), []int{8}
}

func (x *SubscribePaymentRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SubscribePaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

var File_proto_devicebridge_v1_payment_proto protoreflect.FileDescriptor

const file_proto_devicebridge_v1_payment_proto_rawDesc = "" +
	"\n" +
	"#proto/devicebridge/v1/payment.proto\x12\x0fdevicebridge.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc1\x02\n" +
	"\x13StartPaymentRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12-\n" +
	"\x12merchant_reference\x18\x04 \x01(\tR\x11merchantReference\x12N\n" +
	"\bmetadata\x18\x05 \x03(\v22.devicebridge.v1.StartPaymentRequest.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x06 \x01(\x05R\ttimeoutMs\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xab\x01\n" +
	"\x14StartPaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.devicebridge.v1.PaymentStateR\x06status\x12=\n" +
	"\finitiated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vinitiatedAt\"R\n" +
	"\x14CancelPaymentRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\"1\n" +
	"\x15CancelPaymentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"U\n" +
	"\x17GetPaymentStatusRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\"\x86\x03\n" +
	"\rPaymentStatus\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.devicebridge.v1.PaymentStateR\x06status\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1b\n" +
	"\tcard_type\x18\x05 \x01(\tR\bcardType\x12\x15\n" +
	"\x06last_4\x18\x06 \x01(\tR\x05last4\x12#\n" +
	"\rapproval_code\x18\a \x01(\tR\fapprovalCode\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12=\n" +
	"\finitiated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vinitiatedAt\x12=\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"R\n" +
	"\x18GetPaymentStatusResponse\x126\n" +
	"\x06status\x18\x01 \x01(\v2\x1e.devicebridge.v1.PaymentStatusR\x06status\"\xce\x01\n" +
	"\fPaymentEvent\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x125\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1d.devicebridge.v1.PaymentStateR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"U\n" +
	"\x17SubscribePaymentRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId*\xf2\x01\n" +
	"\fPaymentState\x12\x1d\n" +
	"\x19PAYMENT_STATE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PAYMENT_STATE_INITIATED\x10\x01\x12\x1d\n" +
	"\x19PAYMENT_STATE_IN_PROGRESS\x10\x02\x12\x1a\n" +
	"\x16PAYMENT_STATE_APPROVED\x10\x03\x12\x1a\n" +
	"\x16PAYMENT_STATE_DECLINED\x10\x04\x12\x1b\n" +
	"\x17PAYMENT_STATE_CANCELLED\x10\x05\x12\x19\n" +
	"\x15PAYMENT_STATE_TIMEOUT\x10\x06\x12\x17\n" +
	"\x13PAYMENT_STATE_ERROR\x10\aBJZHgithub.com/Macber-eg/Flutter-Device/proto/devicebridge/v1;devicebridgev1b\x06proto3"

var (
	file_proto_devicebridge_v1_payment_proto_rawDescOnce sync.Once
	file_proto_devicebridge_v1_payment_proto_rawDescData []byte
)

func file_proto_devicebridge_v1_payment_proto_rawDescGZIP() []byte {
	file_proto_devicebridge_v1_payment_proto_rawDescOnce.Do(func() {
		file_proto_devicebridge_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_devicebridge_v1_payment_proto_rawDesc), len(file_proto_devicebridge_v1_payment_proto_rawDesc)))
	})
	return file_proto_devicebridge_v1_payment_proto_rawDescData
}

var file_proto_devicebridge_v1_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_devicebridge_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_devicebridge_v1_payment_proto_goTypes = []any{
	(PaymentState)(0),                // 0: devicebridge.v1.PaymentState
	(*StartPaymentRequest)(nil),      // 1: devicebridge.v1.StartPaymentRequest
	(*StartPaymentResponse)(nil),     // 2: devicebridge.v1.StartPaymentResponse
	(*CancelPaymentRequest)(nil),     // 3: devicebridge.v1.CancelPaymentRequest
	(*CancelPaymentResponse)(nil),    // 4: devicebridge.v1.CancelPaymentResponse
	(*GetPaymentStatusRequest)(nil),  // 5: devicebridge.v1.GetPaymentStatusRequest
	(*PaymentStatus)(nil),            // 6: devicebridge.v1.PaymentStatus
	(*GetPaymentStatusResponse)(nil), // 7: devicebridge.v1.GetPaymentStatusResponse
	(*PaymentEvent)(nil),             // 8: devicebridge.v1.PaymentEvent
	(*SubscribePaymentRequest)(nil),  // 9: devicebridge.v1.SubscribePaymentRequest
	nil,                              // 10: devicebridge.v1.StartPaymentRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil),    // 11: google.protobuf.Timestamp
}
var file_proto_devicebridge_v1_payment_proto_depIdxs = []int32{
	10, // 0: devicebridge.v1.StartPaymentRequest.metadata:type_name -> devicebridge.v1.StartPaymentRequest.MetadataEntry
	0,  // 1: devicebridge.v1.StartPaymentResponse.status:type_name -> devicebridge.v1.PaymentState
	11, // 2: devicebridge.v1.StartPaymentResponse.initiated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: devicebridge.v1.PaymentStatus.status:type_name -> devicebridge.v1.PaymentState
	11, // 4: devicebridge.v1.PaymentStatus.initiated_at:type_name -> google.protobuf.Timestamp
	11, // 5: devicebridge.v1.PaymentStatus.completed_at:type_name -> google.protobuf.Timestamp
	6,  // 6: devicebridge.v1.GetPaymentStatusResponse.status:type_name -> devicebridge.v1.PaymentStatus
	0,  // 7: devicebridge.v1.PaymentEvent.status:type_name -> devicebridge.v1.PaymentState
	11, // 8: devicebridge.v1.PaymentEvent.timestamp:type_name -> google.protobuf.Timestamp
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_devicebridge_v1_payment_proto_init() }
func file_proto_devicebridge_v1_payment_proto_init() {
	if File_proto_devicebridge_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_devicebridge_v1_payment_proto_rawDesc), len(file_proto_devicebridge_v1_payment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_devicebridge_v1_payment_proto_goTypes,
		DependencyIndexes: file_proto_devicebridge_v1_payment_proto_depIdxs,
		EnumInfos:         file_proto_devicebridge_v1_payment_proto_enumTypes,
		MessageInfos:      file_proto_devicebridge_v1_payment_proto_msgTypes,
	}.Build()
	File_proto_devicebridge_v1_payment_proto = out.File
	file_proto_devicebridge_v1_payment_proto_goTypes = nil
	file_proto_devicebridge_v1_payment_proto_depIdxs = nil
}
