// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: proto/devicebridge/v1/printer.proto

package devicebridgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Alignment defines text alignment
type Alignment int32

const (
	Alignment_ALIGNMENT_UNSPECIFIED Alignment = 0
	Alignment_ALIGNMENT_LEFT        Alignment = 1
	Alignment_ALIGNMENT_CENTER      Alignment = 2
	Alignment_ALIGNMENT_RIGHT       Alignment = 3
)

// Enum value maps for Alignment.
var (
	Alignment_name = map[int32]string{
		0: "ALIGNMENT_UNSPECIFIED",
		1: "ALIGNMENT_LEFT",
		2: "ALIGNMENT_CENTER",
		3: "ALIGNMENT_RIGHT",
	}
	Alignment_value = map[string]int32{
		"ALIGNMENT_UNSPECIFIED": 0,
		"ALIGNMENT_LEFT":        1,
		"ALIGNMENT_CENTER":      2,
		"ALIGNMENT_RIGHT":       3,
	}
)

func (x Alignment) Enum() *Alignment {
	p := new(Alignment)
	*p = x
	return p
}

func (x Alignment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Alignment) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_devicebridge_v1_printer_proto_enumTypes[0].Descriptor()
}

func (Alignment) Type() protoreflect.EnumType {
	return &file_proto_devicebridge_v1_printer_proto_enumTypes[0]
}

func (x Alignment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Alignment.Descriptor instead.
func (Alignment) EnumDescriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_printer_proto_rawDescGZIP(), []int{0}
}

// Font selection
type Font int32

const (
	Font_FONT_UNSPECIFIED Font = 0
	Font_FONT_A           Font = 1 // Usually 12x24
	Font_FONT_B           Font = 2 // Usually 9x17
)

// Enum value maps for Font.
var (
	Font_name = map[int32]string{
		0: "FONT_UNSPECIFIED",
		1: "FONT_A",
		2: "FONT_B",
	}
	Font_value = map[string]int32{
		"FONT_UNSPECIFIED": 0,
		"FONT_A":           1,
		"FONT_B":           2,
	}
)

func (x Font) Enum() *Font {
	p := new(Font)
	*p = x
	return p
}

func (x Font) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Font) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_devicebridge_v1_printer_proto_enumTypes[1].Descriptor()
}

func (Font) Type() protoreflect.EnumType {
	return &file_proto_devicebridge_v1_printer_proto_enumTypes[1]
}

func (x Font) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Font.Descriptor instead.
func (Font) EnumDescriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_printer_proto_rawDescGZIP(), []int{1}
}

// BarcodeSymbology defines barcode types
type BarcodeSymbology int32

const (
	BarcodeSymbology_BARCODE_SYMBOLOGY_UNSPECIFIED BarcodeSymbology = 0
	BarcodeSymbology_BARCODE_SYMBOLOGY_UPCA        BarcodeSymbology = 1
	BarcodeSymbology_BARCODE_SYMBOLOGY_UPCE        BarcodeSymbology = 2
	BarcodeSymbology_BARCODE_SYMBOLOGY_EAN13       BarcodeSymbology = 3
	BarcodeSymbology_BARCODE_SYMBOLOGY_EAN8        BarcodeSymbology = 4
	BarcodeSymbology_BARCODE_SYMBOLOGY_CODE39      BarcodeSymbology = 5
	BarcodeSymbology_BARCODE_SYMBOLOGY_CODE128     BarcodeSymbology = 6
	BarcodeSymbology_BARCODE_SYMBOLOGY_ITF         BarcodeSymbology = 7
	BarcodeSymbology_BARCODE_SYMBOLOGY_CODABAR     BarcodeSymbology = 8
)

// Enum value maps for BarcodeSymbology.
var (
	BarcodeSymbology_name = map[int32]string{
		0: "BARCODE_SYMBOLOGY_UNSPECIFIED",
		1: "BARCODE_SYMBOLOGY_UPCA",
		2: "BARCODE_SYMBOLOGY_UPCE",
		3: "BARCODE_SYMBOLOGY_EAN13",
		4: "BARCODE_SYMBOLOGY_EAN8",
		5: "BARCODE_SYMBOLOGY_CODE39",
		6: "BARCODE_SYMBOLOGY_CODE128",
		7: "BARCODE_SYMBOLOGY_ITF",
		8: "BARCODE_SYMBOLOGY_CODABAR",
	}
	BarcodeSymbology_value = map[string]int32{
		"BARCODE_SYMBOLOGY_UNSPECIFIED": 0,
		"BARCODE_SYMBOLOGY_UPCA":        1,
		"BARCODE_SYMBOLOGY_UPCE":        2,
		"BARCODE_SYMBOLOGY_EAN13":       3,
		"BARCODE_SYMBOLOGY_EAN8":        4,
		"BARCODE_SYMBOLOGY_CODE39":      5,
		"BARCODE_SYMBOLOGY_CODE128":     6,
		"BARCODE_SYMBOLOGY_ITF":         7,
		"BARCODE_SYMBOLOGY_CODABAR":     8,
	}
)

func (x BarcodeSymbology) Enum() *BarcodeSymbology {
	p := new(BarcodeSymbology)
	*p = x
	return p
}

func (x BarcodeSymbology) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BarcodeSymbology) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_devicebridge_v1_printer_proto_enumTypes[2].Descriptor()
}

func (BarcodeSymbology) Type() protoreflect.EnumType {
	return &file_proto_devicebridge_v1_printer_proto_enumTypes[2]
}

func (x BarcodeSymbology) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BarcodeSymbology.Descriptor instead.
func (BarcodeSymbology) EnumDescriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_printer_proto_rawDescGZIP(), []int{2}
}

// TextStyle defines text formatting
type TextStyle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bold          bool                   `protobuf:"varint,1,opt,name=bold,proto3" json:"bold,omitempty"`
	Underline     bool                   `protobuf:"varint,2,opt,name=underline,proto3" json:"underline,omitempty"`
	Inverse       bool                   `protobuf:"varint,3,opt,name=inverse,proto3" json:"inverse,omitempty"`
	DoubleWidth   bool                   `protobuf:"varint,4,opt,name=double_width,json=doubleWidth,proto3" json:"double_width,omitempty"`
	DoubleHeight  bool                   `protobuf:"varint,5,opt,name=double_height,json=doubleHeight,proto3" json:"double_height,omitempty"`
	Font          Font                   `protobuf:"varint,6,opt,name=font,proto3,enum=devicebridge.v1.Font" json:"font,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextStyle) Reset() {
	*x = TextStyle{}
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextStyle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextStyle) ProtoMessage() {}

func (x *TextStyle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextStyle.ProtoReflect.Descriptor instead.
func (*TextStyle) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_printer_proto_rawDescGZIP(), []int{0}
}

func (x *TextStyle) GetBold() bool {
	if x != nil {
		return x.Bold
	}
	return false
}

func (x *TextStyle) GetUnderline() bool {
	if x != nil {
		return x.Underline
	}
	return false
}

func (x *TextStyle) GetInverse() bool {
	if x != nil {
		return x.Inverse
	}
	return false
}

func (x *TextStyle) GetDoubleWidth() bool {
	if x != nil {
		return x.DoubleWidth
	}
	return false
}

func (x *TextStyle) GetDoubleHeight() bool {
	if x != nil {
		return x.DoubleHeight
	}
	return false
}

func (x *TextStyle) GetFont() Font {
	if x != nil {
		return x.Font
	}
	return Font_FONT_UNSPECIFIED
}

// Run represents styled text
type Run struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Style         *TextStyle             `protobuf:"bytes,2,opt,name=style,proto3" json:"style,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Run) Reset() {
	*x = Run{}
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Run) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run) ProtoMessage() {}

func (x *Run) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run.ProtoReflect.Descriptor instead.
func (*Run) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_printer_proto_rawDescGZIP(), []int{1}
}

func (x *Run) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Run) GetStyle() *TextStyle {
	if x != nil {
		return x.Style
	}
	return nil
}

// Line represents a single line of output
type Line struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*Run                 `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	Alignment     Alignment              `protobuf:"varint,2,opt,name=alignment,proto3,enum=devicebridge.v1.Alignment" json:"alignment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Line) Reset() {
	*x = Line{}
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Line) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Line) ProtoMessage() {}

func (x *Line) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Line.ProtoReflect.Descriptor instead.
func (*Line) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_printer_proto_rawDescGZIP(), []int{2}
}

func (x *Line) GetRuns() []*Run {
	if x != nil {
		return x.Runs
	}
	return nil
}

func (x *Line) GetAlignment() Alignment {
	if x != nil {
		return x.Alignment
	}
	return Alignment_ALIGNMENT_UNSPECIFIED
}

// Barcode represents a 1D barcode
type Barcode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Symbology     BarcodeSymbology       `protobuf:"varint,2,opt,name=symbology,proto3,enum=devicebridge.v1.BarcodeSymbology" json:"symbology,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Width         int32                  `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Barcode) Reset() {
	*x = Barcode{}
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Barcode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Barcode) ProtoMessage() {}

func (x *Barcode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Barcode.ProtoReflect.Descriptor instead.
func (*Barcode) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_printer_proto_rawDescGZIP(), []int{3}
}

func (x *Barcode) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Barcode) GetSymbology() BarcodeSymbology {
	if x != nil {
		return x.Symbology
	}
	return BarcodeSymbology_BARCODE_SYMBOLOGY_UNSPECIFIED
}

func (x *Barcode) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Barcode) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

// QRCode represents a QR code
type QRCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QRCode) Reset() {
	*x = QRCode{}
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QRCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QRCode) ProtoMessage() {}

func (x *QRCode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QRCode.ProtoReflect.Descriptor instead.
func (*QRCode) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_printer_proto_rawDescGZIP(), []int{4}
}

func (x *QRCode) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *QRCode) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// Image represents a bitmap image
type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // PNG or JPEG
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_printer_proto_rawDescGZIP(), []int{5}
}

func (x *Image) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Image) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Image) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// Element can be text lines, barcode, QR code, or image
type Element struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Element:
	//
	//	*Element_Line
	//	*Element_Barcode
	//	*Element_QrCode
	//	*Element_Image
	Element       isElement_Element `protobuf_oneof:"element"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Element) Reset() {
	*x = Element{}
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Element) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Element) ProtoMessage() {}

func (x *Element) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Element.ProtoReflect.Descriptor instead.
func (*Element) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_printer_proto_rawDescGZIP(), []int{6}
}

func (x *Element) GetElement() isElement_Element {
	if x != nil {
		return x.Element
	}
	return nil
}

func (x *Element) GetLine() *Line {
	if x != nil {
		if x, ok := x.Element.(*Element_Line); ok {
			return x.Line
		}
	}
	return nil
}

func (x *Element) GetBarcode() *Barcode {
	if x != nil {
		if x, ok := x.Element.(*Element_Barcode); ok {
			return x.Barcode
		}
	}
	return nil
}

func (x *Element) GetQrCode() *QRCode {
	if x != nil {
		if x, ok := x.Element.(*Element_QrCode); ok {
			return x.QrCode
		}
	}
	return nil
}

func (x *Element) GetImage() *Image {
	if x != nil {
		if x, ok := x.Element.(*Element_Image); ok {
			return x.Image
		}
	}
	return nil
}

type isElement_Element interface {
	isElement_Element()
}

type Element_Line struct {
	Line *Line `protobuf:"bytes,1,opt,name=line,proto3,oneof"`
}

type Element_Barcode struct {
	Barcode *Barcode `protobuf:"bytes,2,opt,name=barcode,proto3,oneof"`
}

type Element_QrCode struct {
	QrCode *QRCode `protobuf:"bytes,3,opt,name=qr_code,json=qrCode,proto3,oneof"`
}

type Element_Image struct {
	Image *Image `protobuf:"bytes,4,opt,name=image,proto3,oneof"`
}

func (*Element_Line) isElement_Element() {}

func (*Element_Barcode) isElement_Element() {}

func (*Element_QrCode) isElement_Element() {}

func (*Element_Image) isElement_Element() {}

// Section represents a logical grouping
type Section struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elements      []*Element             `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Section) Reset() {
	*x = Section{}
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Section) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Section) ProtoMessage() {}

func (x *Section) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Section.ProtoReflect.Descriptor instead.
func (*Section) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_printer_proto_rawDescGZIP(), []int{7}
}

func (x *Section) GetElements() []*Element {
	if x != nil {
		return x.Elements
	}
	return nil
}

// PrintDocument represents a complete print job
type PrintDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sections      []*Section             `protobuf:"bytes,1,rep,name=sections,proto3" json:"sections,omitempty"`
	Options       *PrintOptions          `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrintDocument) Reset() {
	*x = PrintDocument{}
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrintDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintDocument) ProtoMessage() {}

func (x *PrintDocument) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintDocument.ProtoReflect.Descriptor instead.
func (*PrintDocument) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_printer_proto_rawDescGZIP(), []int{8}
}

func (x *PrintDocument) GetSections() []*Section {
	if x != nil {
		return x.Sections
	}
	return nil
}

func (x *PrintDocument) GetOptions() *PrintOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// PrintOptions contains print job options
type PrintOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cut           bool                   `protobuf:"varint,1,opt,name=cut,proto3" json:"cut,omitempty"`
	DrawerPulse   bool                   `protobuf:"varint,2,opt,name=drawer_pulse,json=drawerPulse,proto3" json:"drawer_pulse,omitempty"`
	Copies        int32                  `protobuf:"varint,3,opt,name=copies,proto3" json:"copies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrintOptions) Reset() {
	*x = PrintOptions{}
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrintOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintOptions) ProtoMessage() {}

func (x *PrintOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintOptions.ProtoReflect.Descriptor instead.
func (*PrintOptions) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_printer_proto_rawDescGZIP(), []int{9}
}

func (x *PrintOptions) GetCut() bool {
	if x != nil {
		return x.Cut
	}
	return false
}

func (x *PrintOptions) GetDrawerPulse() bool {
	if x != nil {
		return x.DrawerPulse
	}
	return false
}

func (x *PrintOptions) GetCopies() int32 {
	if x != nil {
		return x.Copies
	}
	return 0
}

// PrintRequest initiates a print job
type PrintRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceId       string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Document       *PrintDocument         `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrintRequest) Reset() {
	*x = PrintRequest{}
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintRequest) ProtoMessage() {}

func (x *PrintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintRequest.ProtoReflect.Descriptor instead.
func (*PrintRequest) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_printer_proto_rawDescGZIP(), []int{10}
}

func (x *PrintRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PrintRequest) GetDocument() *PrintDocument {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *PrintRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// PrintResponse returns the job ID
type PrintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrintResponse) Reset() {
	*x = PrintResponse{}
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintResponse) ProtoMessage() {}

func (x *PrintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintResponse.ProtoReflect.Descriptor instead.
func (*PrintResponse) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_printer_proto_rawDescGZIP(), []int{11}
}

func (x *PrintResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// OpenDrawerRequest opens a cash drawer
type OpenDrawerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenDrawerRequest) Reset() {
	*x = OpenDrawerRequest{}
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenDrawerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDrawerRequest) ProtoMessage() {}

func (x *OpenDrawerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDrawerRequest.ProtoReflect.Descriptor instead.
func (*OpenDrawerRequest) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_printer_proto_rawDescGZIP(), []int{12}
}

func (x *OpenDrawerRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// OpenDrawerResponse confirms drawer opening
type OpenDrawerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	OpenedAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=opened_at,json=openedAt,proto3" json:"opened_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenDrawerResponse) Reset() {
	*x = OpenDrawerResponse{}
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenDrawerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDrawerResponse) ProtoMessage() {}

func (x *OpenDrawerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_printer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDrawerResponse.ProtoReflect.Descriptor instead.
func (*OpenDrawerResponse) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_printer_proto_rawDescGZIP(), []int{13}
}

func (x *OpenDrawerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OpenDrawerResponse) GetOpenedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OpenedAt
	}
	return nil
}

var File_proto_devicebridge_v1_printer_proto protoreflect.FileDescriptor

const file_proto_devicebridge_v1_printer_proto_rawDesc = "" +
	"\n" +
	"#proto/devicebridge/v1/printer.proto\x12\x0fdevicebridge.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\"proto/devicebridge/v1/common.proto\"\xca\x01\n" +
	"\tTextStyle\x12\x12\n" +
	"\x04bold\x18\x01 \x01(\bR\x04bold\x12\x1c\n" +
	"\tunderline\x18\x02 \x01(\bR\tunderline\x12\x18\n" +
	"\ainverse\x18\x03 \x01(\bR\ainverse\x12!\n" +
	"\fdouble_width\x18\x04 \x01(\bR\vdoubleWidth\x12#\n" +
	"\rdouble_height\x18\x05 \x01(\bR\fdoubleHeight\x12)\n" +
	"\x04font\x18\x06 \x01(\x0e2\x15.devicebridge.v1.FontR\x04font\"K\n" +
	"\x03Run\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x120\n" +
	"\x05style\x18\x02 \x01(\v2\x1a.devicebridge.v1.TextStyleR\x05style\"j\n" +
	"\x04Line\x12(\n" +
	"\x04runs\x18\x01 \x03(\v2\x14.devicebridge.v1.RunR\x04runs\x128\n" +
	"\talignment\x18\x02 \x01(\x0e2\x1a.devicebridge.v1.AlignmentR\talignment\"\x8c\x01\n" +
	"\aBarcode\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12?\n" +
	"\tsymbology\x18\x02 \x01(\x0e2!.devicebridge.v1.BarcodeSymbologyR\tsymbology\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x05R\x05width\"0\n" +
	"\x06QRCode\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"I\n" +
	"\x05Image\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\"\xdb\x01\n" +
	"\aElement\x12+\n" +
	"\x04line\x18\x01 \x01(\v2\x15.devicebridge.v1.LineH\x00R\x04line\x124\n" +
	"\abarcode\x18\x02 \x01(\v2\x18.devicebridge.v1.BarcodeH\x00R\abarcode\x122\n" +
	"\aqr_code\x18\x03 \x01(\v2\x17.devicebridge.v1.QRCodeH\x00R\x06qrCode\x12.\n" +
	"\x05image\x18\x04 \x01(\v2\x16.devicebridge.v1.ImageH\x00R\x05imageB\t\n" +
	"\aelement\"?\n" +
	"\aSection\x124\n" +
	"\belements\x18\x01 \x03(\v2\x18.devicebridge.v1.ElementR\belements\"~\n" +
	"\rPrintDocument\x124\n" +
	"\bsections\x18\x01 \x03(\v2\x18.devicebridge.v1.SectionR\bsections\x127\n" +
	"\aoptions\x18\x02 \x01(\v2\x1d.devicebridge.v1.PrintOptionsR\aoptions\"[\n" +
	"\fPrintOptions\x12\x10\n" +
	"\x03cut\x18\x01 \x01(\bR\x03cut\x12!\n" +
	"\fdrawer_pulse\x18\x02 \x01(\bR\vdrawerPulse\x12\x16\n" +
	"\x06copies\x18\x03 \x01(\x05R\x06copies\"\x90\x01\n" +
	"\fPrintRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12:\n" +
	"\bdocument\x18\x02 \x01(\v2\x1e.devicebridge.v1.PrintDocumentR\bdocument\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"&\n" +
	"\rPrintResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"0\n" +
	"\x11OpenDrawerRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"g\n" +
	"\x12OpenDrawerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x127\n" +
	"\topened_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bopenedAt*e\n" +
	"\tAlignment\x12\x19\n" +
	"\x15ALIGNMENT_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eALIGNMENT_LEFT\x10\x01\x12\x14\n" +
	"\x10ALIGNMENT_CENTER\x10\x02\x12\x13\n" +
	"\x0fALIGNMENT_RIGHT\x10\x03*4\n" +
	"\x04Font\x12\x14\n" +
	"\x10FONT_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06FONT_A\x10\x01\x12\n" +
	"\n" +
	"\x06FONT_B\x10\x02*\x9d\x02\n" +
	"\x10BarcodeSymbology\x12!\n" +
	"\x1dBARCODE_SYMBOLOGY_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16BARCODE_SYMBOLOGY_UPCA\x10\x01\x12\x1a\n" +
	"\x16BARCODE_SYMBOLOGY_UPCE\x10\x02\x12\x1b\n" +
	"\x17BARCODE_SYMBOLOGY_EAN13\x10\x03\x12\x1a\n" +
	"\x16BARCODE_SYMBOLOGY_EAN8\x10\x04\x12\x1c\n" +
	"\x18BARCODE_SYMBOLOGY_CODE39\x10\x05\x12\x1d\n" +
	"\x19BARCODE_SYMBOLOGY_CODE128\x10\x06\x12\x19\n" +
	"\x15BARCODE_SYMBOLOGY_ITF\x10\a\x12\x1d\n" +
	"\x19BARCODE_SYMBOLOGY_CODABAR\x10\bBJZHgithub.com/Macber-eg/Flutter-Device/proto/devicebridge/v1;devicebridgev1b\x06proto3"

var (
	file_proto_devicebridge_v1_printer_proto_rawDescOnce sync.Once
	file_proto_devicebridge_v1_printer_proto_rawDescData []byte
)

func file_proto_devicebridge_v1_printer_proto_rawDescGZIP() []byte {
	file_proto_devicebridge_v1_printer_proto_rawDescOnce.Do(func() {
		file_proto_devicebridge_v1_printer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_devicebridge_v1_printer_proto_rawDesc), len(file_proto_devicebridge_v1_printer_proto_rawDesc)))
	})
	return file_proto_devicebridge_v1_printer_proto_rawDescData
}

var file_proto_devicebridge_v1_printer_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_devicebridge_v1_printer_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_devicebridge_v1_printer_proto_goTypes = []any{
	(Alignment)(0),                // 0: devicebridge.v1.Alignment
	(Font)(0),                     // 1: devicebridge.v1.Font
	(BarcodeSymbology)(0),         // 2: devicebridge.v1.BarcodeSymbology
	(*TextStyle)(nil),             // 3: devicebridge.v1.TextStyle
	(*Run)(nil),                   // 4: devicebridge.v1.Run
	(*Line)(nil),                  // 5: devicebridge.v1.Line
	(*Barcode)(nil),               // 6: devicebridge.v1.Barcode
	(*QRCode)(nil),                // 7: devicebridge.v1.QRCode
	(*Image)(nil),                 // 8: devicebridge.v1.Image
	(*Element)(nil),               // 9: devicebridge.v1.Element
	(*Section)(nil),               // 10: devicebridge.v1.Section
	(*PrintDocument)(nil),         // 11: devicebridge.v1.PrintDocument
	(*PrintOptions)(nil),          // 12: devicebridge.v1.PrintOptions
	(*PrintRequest)(nil),          // 13: devicebridge.v1.PrintRequest
	(*PrintResponse)(nil),         // 14: devicebridge.v1.PrintResponse
	(*OpenDrawerRequest)(nil),     // 15: devicebridge.v1.OpenDrawerRequest
	(*OpenDrawerResponse)(nil),    // 16: devicebridge.v1.OpenDrawerResponse
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_proto_devicebridge_v1_printer_proto_depIdxs = []int32{
	1,  // 0: devicebridge.v1.TextStyle.font:type_name -> devicebridge.v1.Font
	3,  // 1: devicebridge.v1.Run.style:type_name -> devicebridge.v1.TextStyle
	4,  // 2: devicebridge.v1.Line.runs:type_name -> devicebridge.v1.Run
	0,  // 3: devicebridge.v1.Line.alignment:type_name -> devicebridge.v1.Alignment
	2,  // 4: devicebridge.v1.Barcode.symbology:type_name -> devicebridge.v1.BarcodeSymbology
	5,  // 5: devicebridge.v1.Element.line:type_name -> devicebridge.v1.Line
	6,  // 6: devicebridge.v1.Element.barcode:type_name -> devicebridge.v1.Barcode
	7,  // 7: devicebridge.v1.Element.qr_code:type_name -> devicebridge.v1.QRCode
	8,  // 8: devicebridge.v1.Element.image:type_name -> devicebridge.v1.Image
	9,  // 9: devicebridge.v1.Section.elements:type_name -> devicebridge.v1.Element
	10, // 10: devicebridge.v1.PrintDocument.sections:type_name -> devicebridge.v1.Section
	12, // 11: devicebridge.v1.PrintDocument.options:type_name -> devicebridge.v1.PrintOptions
	11, // 12: devicebridge.v1.PrintRequest.document:type_name -> devicebridge.v1.PrintDocument
	17, // 13: devicebridge.v1.OpenDrawerResponse.opened_at:type_name -> google.protobuf.Timestamp
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_devicebridge_v1_printer_proto_init() }
func file_proto_devicebridge_v1_printer_proto_init() {
	if File_proto_devicebridge_v1_printer_proto != nil {
		return
	}
	file_proto_devicebridge_v1_common_proto_init()
	file_proto_devicebridge_v1_printer_proto_msgTypes[6].OneofWrappers = []any{
		(*Element_Line)(nil),
		(*Element_Barcode)(nil),
		(*Element_QrCode)(nil),
		(*Element_Image)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_devicebridge_v1_printer_proto_rawDesc), len(file_proto_devicebridge_v1_printer_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_devicebridge_v1_printer_proto_goTypes,
		DependencyIndexes: file_proto_devicebridge_v1_printer_proto_depIdxs,
		EnumInfos:         file_proto_devicebridge_v1_printer_proto_enumTypes,
		MessageInfos:      file_proto_devicebridge_v1_printer_proto_msgTypes,
	}.Build()
	File_proto_devicebridge_v1_printer_proto = out.File
	file_proto_devicebridge_v1_printer_proto_goTypes = nil
	file_proto_devicebridge_v1_printer_proto_depIdxs = nil
}
