// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: proto/devicebridge/v1/scale.proto

package devicebridgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WeightUnit defines weight measurement units
type WeightUnit int32

const (
	WeightUnit_WEIGHT_UNIT_UNSPECIFIED WeightUnit = 0
	WeightUnit_WEIGHT_UNIT_KG          WeightUnit = 1
	WeightUnit_WEIGHT_UNIT_G           WeightUnit = 2
	WeightUnit_WEIGHT_UNIT_LB          WeightUnit = 3
	WeightUnit_WEIGHT_UNIT_OZ          WeightUnit = 4
)

// Enum value maps for WeightUnit.
var (
	WeightUnit_name = map[int32]string{
		0: "WEIGHT_UNIT_UNSPECIFIED",
		1: "WEIGHT_UNIT_KG",
		2: "WEIGHT_UNIT_G",
		3: "WEIGHT_UNIT_LB",
		4: "WEIGHT_UNIT_OZ",
	}
	WeightUnit_value = map[string]int32{
		"WEIGHT_UNIT_UNSPECIFIED": 0,
		"WEIGHT_UNIT_KG":          1,
		"WEIGHT_UNIT_G":           2,
		"WEIGHT_UNIT_LB":          3,
		"WEIGHT_UNIT_OZ":          4,
	}
)

func (x WeightUnit) Enum() *WeightUnit {
	p := new(WeightUnit)
	*p = x
	return p
}

func (x WeightUnit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WeightUnit) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_devicebridge_v1_scale_proto_enumTypes[0].Descriptor()
}

func (WeightUnit) Type() protoreflect.EnumType {
	return &file_proto_devicebridge_v1_scale_proto_enumTypes[0]
}

func (x WeightUnit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WeightUnit.Descriptor instead.
func (WeightUnit) EnumDescriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_scale_proto_rawDescGZIP(), []int{0}
}

// WeightReading represents a weight measurement
type WeightReading struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weight        float64                `protobuf:"fixed64,1,opt,name=weight,proto3" json:"weight,omitempty"`
	Unit          WeightUnit             `protobuf:"varint,2,opt,name=unit,proto3,enum=devicebridge.v1.WeightUnit" json:"unit,omitempty"`
	Stable        bool                   `protobuf:"varint,3,opt,name=stable,proto3" json:"stable,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeightReading) Reset() {
	*x = WeightReading{}
	mi := &file_proto_devicebridge_v1_scale_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeightReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightReading) ProtoMessage() {}

func (x *WeightReading) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_scale_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightReading.ProtoReflect.Descriptor instead.
func (*WeightReading) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_scale_proto_rawDescGZIP(), []int{0}
}

func (x *WeightReading) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *WeightReading) GetUnit() WeightUnit {
	if x != nil {
		return x.Unit
	}
	return WeightUnit_WEIGHT_UNIT_UNSPECIFIED
}

func (x *WeightReading) GetStable() bool {
	if x != nil {
		return x.Stable
	}
	return false
}

func (x *WeightReading) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// GetWeightRequest requests current weight
type GetWeightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeightRequest) Reset() {
	*x = GetWeightRequest{}
	mi := &file_proto_devicebridge_v1_scale_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeightRequest) ProtoMessage() {}

func (x *GetWeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_scale_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeightRequest.ProtoReflect.Descriptor instead.
func (*GetWeightRequest) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_scale_proto_rawDescGZIP(), []int{1}
}

func (x *GetWeightRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetWeightRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// GetWeightResponse returns weight reading
type GetWeightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reading       *WeightReading         `protobuf:"bytes,1,opt,name=reading,proto3" json:"reading,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeightResponse) Reset() {
	*x = GetWeightResponse{}
	mi := &file_proto_devicebridge_v1_scale_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeightResponse) ProtoMessage() {}

func (x *GetWeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_scale_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeightResponse.ProtoReflect.Descriptor instead.
func (*GetWeightResponse) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_scale_proto_rawDescGZIP(), []int{2}
}

func (x *GetWeightResponse) GetReading() *WeightReading {
	if x != nil {
		return x.Reading
	}
	return nil
}

// ZeroScaleRequest zeros the scale
type ZeroScaleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZeroScaleRequest) Reset() {
	*x = ZeroScaleRequest{}
	mi := &file_proto_devicebridge_v1_scale_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZeroScaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZeroScaleRequest) ProtoMessage() {}

func (x *ZeroScaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_scale_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZeroScaleRequest.ProtoReflect.Descriptor instead.
func (*ZeroScaleRequest) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_scale_proto_rawDescGZIP(), []int{3}
}

func (x *ZeroScaleRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// ZeroScaleResponse confirms zero operation
type ZeroScaleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZeroScaleResponse) Reset() {
	*x = ZeroScaleResponse{}
	mi := &file_proto_devicebridge_v1_scale_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZeroScaleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZeroScaleResponse) ProtoMessage() {}

func (x *ZeroScaleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_scale_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZeroScaleResponse.ProtoReflect.Descriptor instead.
func (*ZeroScaleResponse) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_scale_proto_rawDescGZIP(), []int{4}
}

func (x *ZeroScaleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// TareScaleRequest tares the scale
type TareScaleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TareScaleRequest) Reset() {
	*x = TareScaleRequest{}
	mi := &file_proto_devicebridge_v1_scale_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TareScaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TareScaleRequest) ProtoMessage() {}

func (x *TareScaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_scale_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TareScaleRequest.ProtoReflect.Descriptor instead.
func (*TareScaleRequest) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_scale_proto_rawDescGZIP(), []int{5}
}

func (x *TareScaleRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// TareScaleResponse confirms tare operation
type TareScaleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TareScaleResponse) Reset() {
	*x = TareScaleResponse{}
	mi := &file_proto_devicebridge_v1_scale_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TareScaleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TareScaleResponse) ProtoMessage() {}

func (x *TareScaleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_scale_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TareScaleResponse.ProtoReflect.Descriptor instead.
func (*TareScaleResponse) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_scale_proto_rawDescGZIP(), []int{6}
}

func (x *TareScaleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_devicebridge_v1_scale_proto protoreflect.FileDescriptor

const file_proto_devicebridge_v1_scale_proto_rawDesc = "" +
	"\n" +
	"!proto/devicebridge/v1/scale.proto\x12\x0fdevicebridge.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x01\n" +
	"\rWeightReading\x12\x16\n" +
	"\x06weight\x18\x01 \x01(\x01R\x06weight\x12/\n" +
	"\x04unit\x18\x02 \x01(\x0e2\x1b.devicebridge.v1.WeightUnitR\x04unit\x12\x16\n" +
	"\x06stable\x18\x03 \x01(\bR\x06stable\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"N\n" +
	"\x10GetWeightRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\x05R\ttimeoutMs\"M\n" +
	"\x11GetWeightResponse\x128\n" +
	"\areading\x18\x01 \x01(\v2\x1e.devicebridge.v1.WeightReadingR\areading\"/\n" +
	"\x10ZeroScaleRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"-\n" +
	"\x11ZeroScaleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x10TareScaleRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"-\n" +
	"\x11TareScaleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*x\n" +
	"\n" +
	"WeightUnit\x12\x1b\n" +
	"\x17WEIGHT_UNIT_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eWEIGHT_UNIT_KG\x10\x01\x12\x11\n" +
	"\rWEIGHT_UNIT_G\x10\x02\x12\x12\n" +
	"\x0eWEIGHT_UNIT_LB\x10\x03\x12\x12\n" +
	"\x0eWEIGHT_UNIT_OZ\x10\x04BJZHgithub.com/Macber-eg/Flutter-Device/proto/devicebridge/v1;devicebridgev1b\x06proto3"

var (
	file_proto_devicebridge_v1_scale_proto_rawDescOnce sync.Once
	file_proto_devicebridge_v1_scale_proto_rawDescData []byte
)

func file_proto_devicebridge_v1_scale_proto_rawDescGZIP() []byte {
	file_proto_devicebridge_v1_scale_proto_rawDescOnce.Do(func() {
		file_proto_devicebridge_v1_scale_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_devicebridge_v1_scale_proto_rawDesc), len(file_proto_devicebridge_v1_scale_proto_rawDesc)))
	})
	return file_proto_devicebridge_v1_scale_proto_rawDescData
}

var file_proto_devicebridge_v1_scale_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_devicebridge_v1_scale_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_devicebridge_v1_scale_proto_goTypes = []any{
	(WeightUnit)(0),               // 0: devicebridge.v1.WeightUnit
	(*WeightReading)(nil),         // 1: devicebridge.v1.WeightReading
	(*GetWeightRequest)(nil),      // 2: devicebridge.v1.GetWeightRequest
	(*GetWeightResponse)(nil),     // 3: devicebridge.v1.GetWeightResponse
	(*ZeroScaleRequest)(nil),      // 4: devicebridge.v1.ZeroScaleRequest
	(*ZeroScaleResponse)(nil),     // 5: devicebridge.v1.ZeroScaleResponse
	(*TareScaleRequest)(nil),      // 6: devicebridge.v1.TareScaleRequest
	(*TareScaleResponse)(nil),     // 7: devicebridge.v1.TareScaleResponse
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_proto_devicebridge_v1_scale_proto_depIdxs = []int32{
	0, // 0: devicebridge.v1.WeightReading.unit:type_name -> devicebridge.v1.WeightUnit
	8, // 1: devicebridge.v1.WeightReading.timestamp:type_name -> google.protobuf.Timestamp
	1, // 2: devicebridge.v1.GetWeightResponse.reading:type_name -> devicebridge.v1.WeightReading
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_devicebridge_v1_scale_proto_init() }
func file_proto_devicebridge_v1_scale_proto_init() {
	if File_proto_devicebridge_v1_scale_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_devicebridge_v1_scale_proto_rawDesc), len(file_proto_devicebridge_v1_scale_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_devicebridge_v1_scale_proto_goTypes,
		DependencyIndexes: file_proto_devicebridge_v1_scale_proto_depIdxs,
		EnumInfos:         file_proto_devicebridge_v1_scale_proto_enumTypes,
		MessageInfos:      file_proto_devicebridge_v1_scale_proto_msgTypes,
	}.Build()
	File_proto_devicebridge_v1_scale_proto = out.File
	file_proto_devicebridge_v1_scale_proto_goTypes = nil
	file_proto_devicebridge_v1_scale_proto_depIdxs = nil
}
