// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: proto/devicebridge/v1/scanner.proto

package devicebridgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ScanEvent represents a barcode/QR scan
type ScanEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Symbology     string                 `protobuf:"bytes,3,opt,name=symbology,proto3" json:"symbology,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventId       string                 `protobuf:"bytes,5,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanEvent) Reset() {
	*x = ScanEvent{}
	mi := &file_proto_devicebridge_v1_scanner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanEvent) ProtoMessage() {}

func (x *ScanEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_scanner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanEvent.ProtoReflect.Descriptor instead.
func (*ScanEvent) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_scanner_proto_rawDescGZIP(), []int{0}
}

func (x *ScanEvent) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ScanEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ScanEvent) GetSymbology() string {
	if x != nil {
		return x.Symbology
	}
	return ""
}

func (x *ScanEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ScanEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

// SubscribeScannerRequest subscribes to scanner events
type SubscribeScannerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeScannerRequest) Reset() {
	*x = SubscribeScannerRequest{}
	mi := &file_proto_devicebridge_v1_scanner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeScannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeScannerRequest) ProtoMessage() {}

func (x *SubscribeScannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_scanner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeScannerRequest.ProtoReflect.Descriptor instead.
func (*SubscribeScannerRequest) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_scanner_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeScannerRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

var File_proto_devicebridge_v1_scanner_proto protoreflect.FileDescriptor

const file_proto_devicebridge_v1_scanner_proto_rawDesc = "" +
	"\n" +
	"#proto/devicebridge/v1/scanner.proto\x12\x0fdevicebridge.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x01\n" +
	"\tScanEvent\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12\x1c\n" +
	"\tsymbology\x18\x03 \x01(\tR\tsymbology\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x19\n" +
	"\bevent_id\x18\x05 \x01(\tR\aeventId\"6\n" +
	"\x17SubscribeScannerRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceIdBJZHgithub.com/Macber-eg/Flutter-Device/proto/devicebridge/v1;devicebridgev1b\x06proto3"

var (
	file_proto_devicebridge_v1_scanner_proto_rawDescOnce sync.Once
	file_proto_devicebridge_v1_scanner_proto_rawDescData []byte
)

func file_proto_devicebridge_v1_scanner_proto_rawDescGZIP() []byte {
	file_proto_devicebridge_v1_scanner_proto_rawDescOnce.Do(func() {
		file_proto_devicebridge_v1_scanner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_devicebridge_v1_scanner_proto_rawDesc), len(file_proto_devicebridge_v1_scanner_proto_rawDesc)))
	})
	return file_proto_devicebridge_v1_scanner_proto_rawDescData
}

var file_proto_devicebridge_v1_scanner_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_devicebridge_v1_scanner_proto_goTypes = []any{
	(*ScanEvent)(nil),               // 0: devicebridge.v1.ScanEvent
	(*SubscribeScannerRequest)(nil), // 1: devicebridge.v1.SubscribeScannerRequest
	(*timestamppb.Timestamp)(nil),   // 2: google.protobuf.Timestamp
}
var file_proto_devicebridge_v1_scanner_proto_depIdxs = []int32{
	2, // 0: devicebridge.v1.ScanEvent.timestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_devicebridge_v1_scanner_proto_init() }
func file_proto_devicebridge_v1_scanner_proto_init() {
	if File_proto_devicebridge_v1_scanner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_devicebridge_v1_scanner_proto_rawDesc), len(file_proto_devicebridge_v1_scanner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_devicebridge_v1_scanner_proto_goTypes,
		DependencyIndexes: file_proto_devicebridge_v1_scanner_proto_depIdxs,
		MessageInfos:      file_proto_devicebridge_v1_scanner_proto_msgTypes,
	}.Build()
	File_proto_devicebridge_v1_scanner_proto = out.File
	file_proto_devicebridge_v1_scanner_proto_goTypes = nil
	file_proto_devicebridge_v1_scanner_proto_depIdxs = nil
}
