// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: proto/devicebridge/v1/service.proto

package devicebridgev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeviceBridge_Ping_FullMethodName             = "/devicebridge.v1.DeviceBridge/Ping"
	DeviceBridge_ListDevices_FullMethodName      = "/devicebridge.v1.DeviceBridge/ListDevices"
	DeviceBridge_GetDevice_FullMethodName        = "/devicebridge.v1.DeviceBridge/GetDevice"
	DeviceBridge_Print_FullMethodName            = "/devicebridge.v1.DeviceBridge/Print"
	DeviceBridge_OpenDrawer_FullMethodName       = "/devicebridge.v1.DeviceBridge/OpenDrawer"
	DeviceBridge_SubscribeScanner_FullMethodName = "/devicebridge.v1.DeviceBridge/SubscribeScanner"
	DeviceBridge_GetWeight_FullMethodName        = "/devicebridge.v1.DeviceBridge/GetWeight"
	DeviceBridge_ZeroScale_FullMethodName        = "/devicebridge.v1.DeviceBridge/ZeroScale"
	DeviceBridge_TareScale_FullMethodName        = "/devicebridge.v1.DeviceBridge/TareScale"
	DeviceBridge_ShowDisplay_FullMethodName      = "/devicebridge.v1.DeviceBridge/ShowDisplay"
	DeviceBridge_ClearDisplay_FullMethodName     = "/devicebridge.v1.DeviceBridge/ClearDisplay"
	DeviceBridge_StartPayment_FullMethodName     = "/devicebridge.v1.DeviceBridge/StartPayment"
	DeviceBridge_CancelPayment_FullMethodName    = "/devicebridge.v1.DeviceBridge/CancelPayment"
	DeviceBridge_GetPaymentStatus_FullMethodName = "/devicebridge.v1.DeviceBridge/GetPaymentStatus"
	DeviceBridge_SubscribePayment_FullMethodName = "/devicebridge.v1.DeviceBridge/SubscribePayment"
	DeviceBridge_GetJob_FullMethodName           = "/devicebridge.v1.DeviceBridge/GetJob"
)

// DeviceBridgeClient is the client API for DeviceBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DeviceBridge is the main service
type DeviceBridgeClient interface {
	// Ping checks if service is alive
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// ListDevices returns all registered devices
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	// GetDevice returns device details
	GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error)
	// Print sends a document to a printer
	Print(ctx context.Context, in *PrintRequest, opts ...grpc.CallOption) (*PrintResponse, error)
	// OpenDrawer opens a cash drawer
	OpenDrawer(ctx context.Context, in *OpenDrawerRequest, opts ...grpc.CallOption) (*OpenDrawerResponse, error)
	// SubscribeScanner streams barcode scan events
	SubscribeScanner(ctx context.Context, in *SubscribeScannerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanEvent], error)
	// GetWeight reads current weight from scale
	GetWeight(ctx context.Context, in *GetWeightRequest, opts ...grpc.CallOption) (*GetWeightResponse, error)
	// ZeroScale zeros the scale
	ZeroScale(ctx context.Context, in *ZeroScaleRequest, opts ...grpc.CallOption) (*ZeroScaleResponse, error)
	// TareScale tares the scale
	TareScale(ctx context.Context, in *TareScaleRequest, opts ...grpc.CallOption) (*TareScaleResponse, error)
	// ShowDisplay shows text on customer display
	ShowDisplay(ctx context.Context, in *ShowDisplayRequest, opts ...grpc.CallOption) (*ShowDisplayResponse, error)
	// ClearDisplay clears the display
	ClearDisplay(ctx context.Context, in *ClearDisplayRequest, opts ...grpc.CallOption) (*ClearDisplayResponse, error)
	// StartPayment initiates a payment transaction
	StartPayment(ctx context.Context, in *StartPaymentRequest, opts ...grpc.CallOption) (*StartPaymentResponse, error)
	// CancelPayment cancels a payment
	CancelPayment(ctx context.Context, in *CancelPaymentRequest, opts ...grpc.CallOption) (*CancelPaymentResponse, error)
	// GetPaymentStatus queries payment status
	GetPaymentStatus(ctx context.Context, in *GetPaymentStatusRequest, opts ...grpc.CallOption) (*GetPaymentStatusResponse, error)
	// SubscribePayment streams payment events
	SubscribePayment(ctx context.Context, in *SubscribePaymentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PaymentEvent], error)
	// GetJob returns job status
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error)
}

type deviceBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceBridgeClient(cc grpc.ClientConnInterface) DeviceBridgeClient {
	return &deviceBridgeClient{cc}
}

func (c *deviceBridgeClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, DeviceBridge_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceBridgeClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, DeviceBridge_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceBridgeClient) GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeviceResponse)
	err := c.cc.Invoke(ctx, DeviceBridge_GetDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceBridgeClient) Print(ctx context.Context, in *PrintRequest, opts ...grpc.CallOption) (*PrintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintResponse)
	err := c.cc.Invoke(ctx, DeviceBridge_Print_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceBridgeClient) OpenDrawer(ctx context.Context, in *OpenDrawerRequest, opts ...grpc.CallOption) (*OpenDrawerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenDrawerResponse)
	err := c.cc.Invoke(ctx, DeviceBridge_OpenDrawer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceBridgeClient) SubscribeScanner(ctx context.Context, in *SubscribeScannerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeviceBridge_ServiceDesc.Streams[0], DeviceBridge_SubscribeScanner_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeScannerRequest, ScanEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeviceBridge_SubscribeScannerClient = grpc.ServerStreamingClient[ScanEvent]

func (c *deviceBridgeClient) GetWeight(ctx context.Context, in *GetWeightRequest, opts ...grpc.CallOption) (*GetWeightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWeightResponse)
	err := c.cc.Invoke(ctx, DeviceBridge_GetWeight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceBridgeClient) ZeroScale(ctx context.Context, in *ZeroScaleRequest, opts ...grpc.CallOption) (*ZeroScaleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ZeroScaleResponse)
	err := c.cc.Invoke(ctx, DeviceBridge_ZeroScale_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceBridgeClient) TareScale(ctx context.Context, in *TareScaleRequest, opts ...grpc.CallOption) (*TareScaleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TareScaleResponse)
	err := c.cc.Invoke(ctx, DeviceBridge_TareScale_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceBridgeClient) ShowDisplay(ctx context.Context, in *ShowDisplayRequest, opts ...grpc.CallOption) (*ShowDisplayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShowDisplayResponse)
	err := c.cc.Invoke(ctx, DeviceBridge_ShowDisplay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceBridgeClient) ClearDisplay(ctx context.Context, in *ClearDisplayRequest, opts ...grpc.CallOption) (*ClearDisplayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearDisplayResponse)
	err := c.cc.Invoke(ctx, DeviceBridge_ClearDisplay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceBridgeClient) StartPayment(ctx context.Context, in *StartPaymentRequest, opts ...grpc.CallOption) (*StartPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartPaymentResponse)
	err := c.cc.Invoke(ctx, DeviceBridge_StartPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceBridgeClient) CancelPayment(ctx context.Context, in *CancelPaymentRequest, opts ...grpc.CallOption) (*CancelPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelPaymentResponse)
	err := c.cc.Invoke(ctx, DeviceBridge_CancelPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceBridgeClient) GetPaymentStatus(ctx context.Context, in *GetPaymentStatusRequest, opts ...grpc.CallOption) (*GetPaymentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentStatusResponse)
	err := c.cc.Invoke(ctx, DeviceBridge_GetPaymentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceBridgeClient) SubscribePayment(ctx context.Context, in *SubscribePaymentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PaymentEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeviceBridge_ServiceDesc.Streams[1], DeviceBridge_SubscribePayment_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribePaymentRequest, PaymentEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeviceBridge_SubscribePaymentClient = grpc.ServerStreamingClient[PaymentEvent]

func (c *deviceBridgeClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobResponse)
	err := c.cc.Invoke(ctx, DeviceBridge_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceBridgeServer is the server API for DeviceBridge service.
// All implementations must embed UnimplementedDeviceBridgeServer
// for forward compatibility.
//
// DeviceBridge is the main service
type DeviceBridgeServer interface {
	// Ping checks if service is alive
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// ListDevices returns all registered devices
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	// GetDevice returns device details
	GetDevice(context.Context, *GetDeviceRequest) (*GetDeviceResponse, error)
	// Print sends a document to a printer
	Print(context.Context, *PrintRequest) (*PrintResponse, error)
	// OpenDrawer opens a cash drawer
	OpenDrawer(context.Context, *OpenDrawerRequest) (*OpenDrawerResponse, error)
	// SubscribeScanner streams barcode scan events
	SubscribeScanner(*SubscribeScannerRequest, grpc.ServerStreamingServer[ScanEvent]) error
	// GetWeight reads current weight from scale
	GetWeight(context.Context, *GetWeightRequest) (*GetWeightResponse, error)
	// ZeroScale zeros the scale
	ZeroScale(context.Context, *ZeroScaleRequest) (*ZeroScaleResponse, error)
	// TareScale tares the scale
	TareScale(context.Context, *TareScaleRequest) (*TareScaleResponse, error)
	// ShowDisplay shows text on customer display
	ShowDisplay(context.Context, *ShowDisplayRequest) (*ShowDisplayResponse, error)
	// ClearDisplay clears the display
	ClearDisplay(context.Context, *ClearDisplayRequest) (*ClearDisplayResponse, error)
	// StartPayment initiates a payment transaction
	StartPayment(context.Context, *StartPaymentRequest) (*StartPaymentResponse, error)
	// CancelPayment cancels a payment
	CancelPayment(context.Context, *CancelPaymentRequest) (*CancelPaymentResponse, error)
	// GetPaymentStatus queries payment status
	GetPaymentStatus(context.Context, *GetPaymentStatusRequest) (*GetPaymentStatusResponse, error)
	// SubscribePayment streams payment events
	SubscribePayment(*SubscribePaymentRequest, grpc.ServerStreamingServer[PaymentEvent]) error
	// GetJob returns job status
	GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error)
	mustEmbedUnimplementedDeviceBridgeServer()
}

// UnimplementedDeviceBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceBridgeServer struct{}

func (UnimplementedDeviceBridgeServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedDeviceBridgeServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedDeviceBridgeServer) GetDevice(context.Context, *GetDeviceRequest) (*GetDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevice not implemented")
}
func (UnimplementedDeviceBridgeServer) Print(context.Context, *PrintRequest) (*PrintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Print not implemented")
}
func (UnimplementedDeviceBridgeServer) OpenDrawer(context.Context, *OpenDrawerRequest) (*OpenDrawerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenDrawer not implemented")
}
func (UnimplementedDeviceBridgeServer) SubscribeScanner(*SubscribeScannerRequest, grpc.ServerStreamingServer[ScanEvent]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeScanner not implemented")
}
func (UnimplementedDeviceBridgeServer) GetWeight(context.Context, *GetWeightRequest) (*GetWeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWeight not implemented")
}
func (UnimplementedDeviceBridgeServer) ZeroScale(context.Context, *ZeroScaleRequest) (*ZeroScaleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ZeroScale not implemented")
}
func (UnimplementedDeviceBridgeServer) TareScale(context.Context, *TareScaleRequest) (*TareScaleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TareScale not implemented")
}
func (UnimplementedDeviceBridgeServer) ShowDisplay(context.Context, *ShowDisplayRequest) (*ShowDisplayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowDisplay not implemented")
}
func (UnimplementedDeviceBridgeServer) ClearDisplay(context.Context, *ClearDisplayRequest) (*ClearDisplayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearDisplay not implemented")
}
func (UnimplementedDeviceBridgeServer) StartPayment(context.Context, *StartPaymentRequest) (*StartPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartPayment not implemented")
}
func (UnimplementedDeviceBridgeServer) CancelPayment(context.Context, *CancelPaymentRequest) (*CancelPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelPayment not implemented")
}
func (UnimplementedDeviceBridgeServer) GetPaymentStatus(context.Context, *GetPaymentStatusRequest) (*GetPaymentStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaymentStatus not implemented")
}
func (UnimplementedDeviceBridgeServer) SubscribePayment(*SubscribePaymentRequest, grpc.ServerStreamingServer[PaymentEvent]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribePayment not implemented")
}
func (UnimplementedDeviceBridgeServer) GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedDeviceBridgeServer) mustEmbedUnimplementedDeviceBridgeServer() {}
func (UnimplementedDeviceBridgeServer) testEmbeddedByValue()                      {}

// UnsafeDeviceBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceBridgeServer will
// result in compilation errors.
type UnsafeDeviceBridgeServer interface {
	mustEmbedUnimplementedDeviceBridgeServer()
}

func RegisterDeviceBridgeServer(s grpc.ServiceRegistrar, srv DeviceBridgeServer) {
	// If the following call pancis, it indicates UnimplementedDeviceBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceBridge_ServiceDesc, srv)
}

func _DeviceBridge_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceBridgeServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceBridge_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceBridgeServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceBridge_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceBridgeServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceBridge_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceBridgeServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceBridge_GetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceBridgeServer).GetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceBridge_GetDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceBridgeServer).GetDevice(ctx, req.(*GetDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceBridge_Print_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceBridgeServer).Print(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceBridge_Print_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceBridgeServer).Print(ctx, req.(*PrintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceBridge_OpenDrawer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenDrawerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceBridgeServer).OpenDrawer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceBridge_OpenDrawer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceBridgeServer).OpenDrawer(ctx, req.(*OpenDrawerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceBridge_SubscribeScanner_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeScannerRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeviceBridgeServer).SubscribeScanner(m, &grpc.GenericServerStream[SubscribeScannerRequest, ScanEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeviceBridge_SubscribeScannerServer = grpc.ServerStreamingServer[ScanEvent]

func _DeviceBridge_GetWeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceBridgeServer).GetWeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceBridge_GetWeight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceBridgeServer).GetWeight(ctx, req.(*GetWeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceBridge_ZeroScale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZeroScaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceBridgeServer).ZeroScale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceBridge_ZeroScale_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceBridgeServer).ZeroScale(ctx, req.(*ZeroScaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceBridge_TareScale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TareScaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceBridgeServer).TareScale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceBridge_TareScale_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceBridgeServer).TareScale(ctx, req.(*TareScaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceBridge_ShowDisplay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowDisplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceBridgeServer).ShowDisplay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceBridge_ShowDisplay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceBridgeServer).ShowDisplay(ctx, req.(*ShowDisplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceBridge_ClearDisplay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearDisplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceBridgeServer).ClearDisplay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceBridge_ClearDisplay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceBridgeServer).ClearDisplay(ctx, req.(*ClearDisplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceBridge_StartPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceBridgeServer).StartPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceBridge_StartPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceBridgeServer).StartPayment(ctx, req.(*StartPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceBridge_CancelPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceBridgeServer).CancelPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceBridge_CancelPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceBridgeServer).CancelPayment(ctx, req.(*CancelPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceBridge_GetPaymentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceBridgeServer).GetPaymentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceBridge_GetPaymentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceBridgeServer).GetPaymentStatus(ctx, req.(*GetPaymentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceBridge_SubscribePayment_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribePaymentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeviceBridgeServer).SubscribePayment(m, &grpc.GenericServerStream[SubscribePaymentRequest, PaymentEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeviceBridge_SubscribePaymentServer = grpc.ServerStreamingServer[PaymentEvent]

func _DeviceBridge_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceBridgeServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceBridge_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceBridgeServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceBridge_ServiceDesc is the grpc.ServiceDesc for DeviceBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devicebridge.v1.DeviceBridge",
	HandlerType: (*DeviceBridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _DeviceBridge_Ping_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _DeviceBridge_ListDevices_Handler,
		},
		{
			MethodName: "GetDevice",
			Handler:    _DeviceBridge_GetDevice_Handler,
		},
		{
			MethodName: "Print",
			Handler:    _DeviceBridge_Print_Handler,
		},
		{
			MethodName: "OpenDrawer",
			Handler:    _DeviceBridge_OpenDrawer_Handler,
		},
		{
			MethodName: "GetWeight",
			Handler:    _DeviceBridge_GetWeight_Handler,
		},
		{
			MethodName: "ZeroScale",
			Handler:    _DeviceBridge_ZeroScale_Handler,
		},
		{
			MethodName: "TareScale",
			Handler:    _DeviceBridge_TareScale_Handler,
		},
		{
			MethodName: "ShowDisplay",
			Handler:    _DeviceBridge_ShowDisplay_Handler,
		},
		{
			MethodName: "ClearDisplay",
			Handler:    _DeviceBridge_ClearDisplay_Handler,
		},
		{
			MethodName: "StartPayment",
			Handler:    _DeviceBridge_StartPayment_Handler,
		},
		{
			MethodName: "CancelPayment",
			Handler:    _DeviceBridge_CancelPayment_Handler,
		},
		{
			MethodName: "GetPaymentStatus",
			Handler:    _DeviceBridge_GetPaymentStatus_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _DeviceBridge_GetJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeScanner",
			Handler:       _DeviceBridge_SubscribeScanner_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribePayment",
			Handler:       _DeviceBridge_SubscribePayment_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/devicebridge/v1/service.proto",
}
