// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: proto/devicebridge/v1/service.proto

package devicebridgev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PingRequest checks service health
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_devicebridge_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_service_proto_rawDescGZIP(), []int{0}
}

// PingResponse confirms service is alive
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_devicebridge_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// ListDevicesRequest lists devices with optional filtering
type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KindFilter    string                 `protobuf:"bytes,1,opt,name=kind_filter,json=kindFilter,proto3" json:"kind_filter,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_proto_devicebridge_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListDevicesRequest) GetKindFilter() string {
	if x != nil {
		return x.KindFilter
	}
	return ""
}

func (x *ListDevicesRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// ListDevicesResponse returns devices
type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*Device              `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_proto_devicebridge_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListDevicesResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

// GetDeviceRequest requests device details
type GetDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceRequest) Reset() {
	*x = GetDeviceRequest{}
	mi := &file_proto_devicebridge_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceRequest) ProtoMessage() {}

func (x *GetDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceRequest) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// GetDeviceResponse returns device
type GetDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceResponse) Reset() {
	*x = GetDeviceResponse{}
	mi := &file_proto_devicebridge_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceResponse) ProtoMessage() {}

func (x *GetDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceResponse) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetDeviceResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

// GetJobRequest requests job status
type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_proto_devicebridge_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// GetJobResponse returns job
type GetJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_proto_devicebridge_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_devicebridge_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_devicebridge_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

var File_proto_devicebridge_v1_service_proto protoreflect.FileDescriptor

const file_proto_devicebridge_v1_service_proto_rawDesc = "" +
	"\n" +
	"#proto/devicebridge/v1/service.proto\x12\x0fdevicebridge.v1\x1a\x1cgoogle/api/annotations.proto\x1a\"proto/devicebridge/v1/common.proto\x1a#proto/devicebridge/v1/printer.proto\x1a#proto/devicebridge/v1/scanner.proto\x1a!proto/devicebridge/v1/scale.proto\x1a#proto/devicebridge/v1/display.proto\x1a#proto/devicebridge/v1/payment.proto\"\r\n" +
	"\vPingRequest\"B\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"I\n" +
	"\x12ListDevicesRequest\x12\x1f\n" +
	"\vkind_filter\x18\x01 \x01(\tR\n" +
	"kindFilter\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\"H\n" +
	"\x13ListDevicesResponse\x121\n" +
	"\adevices\x18\x01 \x03(\v2\x17.devicebridge.v1.DeviceR\adevices\"/\n" +
	"\x10GetDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"D\n" +
	"\x11GetDeviceResponse\x12/\n" +
	"\x06device\x18\x01 \x01(\v2\x17.devicebridge.v1.DeviceR\x06device\"&\n" +
	"\rGetJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"8\n" +
	"\x0eGetJobResponse\x12&\n" +
	"\x03job\x18\x01 \x01(\v2\x14.devicebridge.v1.JobR\x03job2\xb7\x10\n" +
	"\fDeviceBridge\x12U\n" +
	"\x04Ping\x12\x1c.devicebridge.v1.PingRequest\x1a\x1d.devicebridge.v1.PingResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/ping\x12m\n" +
	"\vListDevices\x12#.devicebridge.v1.ListDevicesRequest\x1a$.devicebridge.v1.ListDevicesResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/devices\x12s\n" +
	"\tGetDevice\x12!.devicebridge.v1.GetDeviceRequest\x1a\".devicebridge.v1.GetDeviceResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/devices/{device_id}\x12p\n" +
	"\x05Print\x12\x1d.devicebridge.v1.PrintRequest\x1a\x1e.devicebridge.v1.PrintResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/devices/{device_id}/print\x12\x85\x01\n" +
	"\n" +
	"OpenDrawer\x12\".devicebridge.v1.OpenDrawerRequest\x1a#.devicebridge.v1.OpenDrawerResponse\".\x82\xd3\xe4\x93\x02(:\x01*\"#/v1/devices/{device_id}/drawer/open\x12\x8a\x01\n" +
	"\x10SubscribeScanner\x12(.devicebridge.v1.SubscribeScannerRequest\x1a\x1a.devicebridge.v1.ScanEvent\".\x82\xd3\xe4\x93\x02(\x12&/v1/devices/{device_id}/scanner/events0\x01\x12z\n" +
	"\tGetWeight\x12!.devicebridge.v1.GetWeightRequest\x1a\".devicebridge.v1.GetWeightResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/devices/{device_id}/weight\x12\x81\x01\n" +
	"\tZeroScale\x12!.devicebridge.v1.ZeroScaleRequest\x1a\".devicebridge.v1.ZeroScaleResponse\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/devices/{device_id}/scale/zero\x12\x81\x01\n" +
	"\tTareScale\x12!.devicebridge.v1.TareScaleRequest\x1a\".devicebridge.v1.TareScaleResponse\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/devices/{device_id}/scale/tare\x12\x89\x01\n" +
	"\vShowDisplay\x12#.devicebridge.v1.ShowDisplayRequest\x1a$.devicebridge.v1.ShowDisplayResponse\"/\x82\xd3\xe4\x93\x02):\x01*\"$/v1/devices/{device_id}/display/show\x12\x8d\x01\n" +
	"\fClearDisplay\x12$.devicebridge.v1.ClearDisplayRequest\x1a%.devicebridge.v1.ClearDisplayResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/v1/devices/{device_id}/display/clear\x12\x8d\x01\n" +
	"\fStartPayment\x12$.devicebridge.v1.StartPaymentRequest\x1a%.devicebridge.v1.StartPaymentResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/v1/devices/{device_id}/payment/start\x12\x91\x01\n" +
	"\rCancelPayment\x12%.devicebridge.v1.CancelPaymentRequest\x1a&.devicebridge.v1.CancelPaymentResponse\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/v1/devices/{device_id}/payment/cancel\x12\x9d\x01\n" +
	"\x10GetPaymentStatus\x12(.devicebridge.v1.GetPaymentStatusRequest\x1a).devicebridge.v1.GetPaymentStatusResponse\"4\x82\xd3\xe4\x93\x02.\x12,/v1/devices/{device_id}/payment/{payment_id}\x12\x9a\x01\n" +
	"\x10SubscribePayment\x12(.devicebridge.v1.SubscribePaymentRequest\x1a\x1d.devicebridge.v1.PaymentEvent\";\x82\xd3\xe4\x93\x025\x123/v1/devices/{device_id}/payment/{payment_id}/events0\x01\x12d\n" +
	"\x06GetJob\x12\x1e.devicebridge.v1.GetJobRequest\x1a\x1f.devicebridge.v1.GetJobResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/jobs/{job_id}BJZHgithub.com/Macber-eg/Flutter-Device/proto/devicebridge/v1;devicebridgev1b\x06proto3"

var (
	file_proto_devicebridge_v1_service_proto_rawDescOnce sync.Once
	file_proto_devicebridge_v1_service_proto_rawDescData []byte
)

func file_proto_devicebridge_v1_service_proto_rawDescGZIP() []byte {
	file_proto_devicebridge_v1_service_proto_rawDescOnce.Do(func() {
		file_proto_devicebridge_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_devicebridge_v1_service_proto_rawDesc), len(file_proto_devicebridge_v1_service_proto_rawDesc)))
	})
	return file_proto_devicebridge_v1_service_proto_rawDescData
}

var file_proto_devicebridge_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_devicebridge_v1_service_proto_goTypes = []any{
	(*PingRequest)(nil),              // 0: devicebridge.v1.PingRequest
	(*PingResponse)(nil),             // 1: devicebridge.v1.PingResponse
	(*ListDevicesRequest)(nil),       // 2: devicebridge.v1.ListDevicesRequest
	(*ListDevicesResponse)(nil),      // 3: devicebridge.v1.ListDevicesResponse
	(*GetDeviceRequest)(nil),         // 4: devicebridge.v1.GetDeviceRequest
	(*GetDeviceResponse)(nil),        // 5: devicebridge.v1.GetDeviceResponse
	(*GetJobRequest)(nil),            // 6: devicebridge.v1.GetJobRequest
	(*GetJobResponse)(nil),           // 7: devicebridge.v1.GetJobResponse
	(*Device)(nil),                   // 8: devicebridge.v1.Device
	(*Job)(nil),                      // 9: devicebridge.v1.Job
	(*PrintRequest)(nil),             // 10: devicebridge.v1.PrintRequest
	(*OpenDrawerRequest)(nil),        // 11: devicebridge.v1.OpenDrawerRequest
	(*SubscribeScannerRequest)(nil),  // 12: devicebridge.v1.SubscribeScannerRequest
	(*GetWeightRequest)(nil),         // 13: devicebridge.v1.GetWeightRequest
	(*ZeroScaleRequest)(nil),         // 14: devicebridge.v1.ZeroScaleRequest
	(*TareScaleRequest)(nil),         // 15: devicebridge.v1.TareScaleRequest
	(*ShowDisplayRequest)(nil),       // 16: devicebridge.v1.ShowDisplayRequest
	(*ClearDisplayRequest)(nil),      // 17: devicebridge.v1.ClearDisplayRequest
	(*StartPaymentRequest)(nil),      // 18: devicebridge.v1.StartPaymentRequest
	(*CancelPaymentRequest)(nil),     // 19: devicebridge.v1.CancelPaymentRequest
	(*GetPaymentStatusRequest)(nil),  // 20: devicebridge.v1.GetPaymentStatusRequest
	(*SubscribePaymentRequest)(nil),  // 21: devicebridge.v1.SubscribePaymentRequest
	(*PrintResponse)(nil),            // 22: devicebridge.v1.PrintResponse
	(*OpenDrawerResponse)(nil),       // 23: devicebridge.v1.OpenDrawerResponse
	(*ScanEvent)(nil),                // 24: devicebridge.v1.ScanEvent
	(*GetWeightResponse)(nil),        // 25: devicebridge.v1.GetWeightResponse
	(*ZeroScaleResponse)(nil),        // 26: devicebridge.v1.ZeroScaleResponse
	(*TareScaleResponse)(nil),        // 27: devicebridge.v1.TareScaleResponse
	(*ShowDisplayResponse)(nil),      // 28: devicebridge.v1.ShowDisplayResponse
	(*ClearDisplayResponse)(nil),     // 29: devicebridge.v1.ClearDisplayResponse
	(*StartPaymentResponse)(nil),     // 30: devicebridge.v1.StartPaymentResponse
	(*CancelPaymentResponse)(nil),    // 31: devicebridge.v1.CancelPaymentResponse
	(*GetPaymentStatusResponse)(nil), // 32: devicebridge.v1.GetPaymentStatusResponse
	(*PaymentEvent)(nil),             // 33: devicebridge.v1.PaymentEvent
}
var file_proto_devicebridge_v1_service_proto_depIdxs = []int32{
	8,  // 0: devicebridge.v1.ListDevicesResponse.devices:type_name -> devicebridge.v1.Device
	8,  // 1: devicebridge.v1.GetDeviceResponse.device:type_name -> devicebridge.v1.Device
	9,  // 2: devicebridge.v1.GetJobResponse.job:type_name -> devicebridge.v1.Job
	0,  // 3: devicebridge.v1.DeviceBridge.Ping:input_type -> devicebridge.v1.PingRequest
	2,  // 4: devicebridge.v1.DeviceBridge.ListDevices:input_type -> devicebridge.v1.ListDevicesRequest
	4,  // 5: devicebridge.v1.DeviceBridge.GetDevice:input_type -> devicebridge.v1.GetDeviceRequest
	10, // 6: devicebridge.v1.DeviceBridge.Print:input_type -> devicebridge.v1.PrintRequest
	11, // 7: devicebridge.v1.DeviceBridge.OpenDrawer:input_type -> devicebridge.v1.OpenDrawerRequest
	12, // 8: devicebridge.v1.DeviceBridge.SubscribeScanner:input_type -> devicebridge.v1.SubscribeScannerRequest
	13, // 9: devicebridge.v1.DeviceBridge.GetWeight:input_type -> devicebridge.v1.GetWeightRequest
	14, // 10: devicebridge.v1.DeviceBridge.ZeroScale:input_type -> devicebridge.v1.ZeroScaleRequest
	15, // 11: devicebridge.v1.DeviceBridge.TareScale:input_type -> devicebridge.v1.TareScaleRequest
	16, // 12: devicebridge.v1.DeviceBridge.ShowDisplay:input_type -> devicebridge.v1.ShowDisplayRequest
	17, // 13: devicebridge.v1.DeviceBridge.ClearDisplay:input_type -> devicebridge.v1.ClearDisplayRequest
	18, // 14: devicebridge.v1.DeviceBridge.StartPayment:input_type -> devicebridge.v1.StartPaymentRequest
	19, // 15: devicebridge.v1.DeviceBridge.CancelPayment:input_type -> devicebridge.v1.CancelPaymentRequest
	20, // 16: devicebridge.v1.DeviceBridge.GetPaymentStatus:input_type -> devicebridge.v1.GetPaymentStatusRequest
	21, // 17: devicebridge.v1.DeviceBridge.SubscribePayment:input_type -> devicebridge.v1.SubscribePaymentRequest
	6,  // 18: devicebridge.v1.DeviceBridge.GetJob:input_type -> devicebridge.v1.GetJobRequest
	1,  // 19: devicebridge.v1.DeviceBridge.Ping:output_type -> devicebridge.v1.PingResponse
	3,  // 20: devicebridge.v1.DeviceBridge.ListDevices:output_type -> devicebridge.v1.ListDevicesResponse
	5,  // 21: devicebridge.v1.DeviceBridge.GetDevice:output_type -> devicebridge.v1.GetDeviceResponse
	22, // 22: devicebridge.v1.DeviceBridge.Print:output_type -> devicebridge.v1.PrintResponse
	23, // 23: devicebridge.v1.DeviceBridge.OpenDrawer:output_type -> devicebridge.v1.OpenDrawerResponse
	24, // 24: devicebridge.v1.DeviceBridge.SubscribeScanner:output_type -> devicebridge.v1.ScanEvent
	25, // 25: devicebridge.v1.DeviceBridge.GetWeight:output_type -> devicebridge.v1.GetWeightResponse
	26, // 26: devicebridge.v1.DeviceBridge.ZeroScale:output_type -> devicebridge.v1.ZeroScaleResponse
	27, // 27: devicebridge.v1.DeviceBridge.TareScale:output_type -> devicebridge.v1.TareScaleResponse
	28, // 28: devicebridge.v1.DeviceBridge.ShowDisplay:output_type -> devicebridge.v1.ShowDisplayResponse
	29, // 29: devicebridge.v1.DeviceBridge.ClearDisplay:output_type -> devicebridge.v1.ClearDisplayResponse
	30, // 30: devicebridge.v1.DeviceBridge.StartPayment:output_type -> devicebridge.v1.StartPaymentResponse
	31, // 31: devicebridge.v1.DeviceBridge.CancelPayment:output_type -> devicebridge.v1.CancelPaymentResponse
	32, // 32: devicebridge.v1.DeviceBridge.GetPaymentStatus:output_type -> devicebridge.v1.GetPaymentStatusResponse
	33, // 33: devicebridge.v1.DeviceBridge.SubscribePayment:output_type -> devicebridge.v1.PaymentEvent
	7,  // 34: devicebridge.v1.DeviceBridge.GetJob:output_type -> devicebridge.v1.GetJobResponse
	19, // [19:35] is the sub-list for method output_type
	3,  // [3:19] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_devicebridge_v1_service_proto_init() }
func file_proto_devicebridge_v1_service_proto_init() {
	if File_proto_devicebridge_v1_service_proto != nil {
		return
	}
	file_proto_devicebridge_v1_common_proto_init()
	file_proto_devicebridge_v1_printer_proto_init()
	file_proto_devicebridge_v1_scanner_proto_init()
	file_proto_devicebridge_v1_scale_proto_init()
	file_proto_devicebridge_v1_display_proto_init()
	file_proto_devicebridge_v1_payment_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_devicebridge_v1_service_proto_rawDesc), len(file_proto_devicebridge_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_devicebridge_v1_service_proto_goTypes,
		DependencyIndexes: file_proto_devicebridge_v1_service_proto_depIdxs,
		MessageInfos:      file_proto_devicebridge_v1_service_proto_msgTypes,
	}.Build()
	File_proto_devicebridge_v1_service_proto = out.File
	file_proto_devicebridge_v1_service_proto_goTypes = nil
	file_proto_devicebridge_v1_service_proto_depIdxs = nil
}
